stretchr/testify

- require/forward_requirements.go
- require/forward_requirements_test.go
- require/requirements.go
The motivation for this PR is to get stop-on-assertion-failure semantics for assert methods in a test suite. Example:
```go
type MySuite struct {
suite.Suite
*require.Assertions // override the default assertions
}
func (s *MySuite) TestAddition() {
s.Equal(3, 1+1) // should fail and exit
s.Equal(5, 2+2) // this failure should not be part of the output
}
```
This PR contains the following changes:
- A new struct `require.Assertions` which is identical to `assert.Assertions` + tests.
- Update the `require` package to match the `assert` package (`Len`, `Regexp`, `NotRegexp` was missing, `Contains` and `NotContains` had different signatures).
- Correct documentation for `require`, which currently states that `bool`s are returned when in fact they aren't.
> Add require.Assertions like assert.Assertions

- README.md
- mock/doc.go
- mock/mock_test.go
These method calls are equivalent, but the former is more concise.
Fixes #95
> Use mockedObj.Method(args) instead of mockedObj.Mock.Method(args).

- assert/assertions.go
Looks like a fmt.Sprintf was left off in the regexp tests.
> Fixed regexp error messages to include input values to aide debugging

- assert/assertions.go
- assert/forward_assertions.go
- require/forward_requirements.go
- require/requirements.go
I've also added the typical `msgAndArgs ...interface{}` argument to the Regexp calls, for consistency's sake.
> Fixed regexp messages.  Resolves #120.

- suite/suite.go
- suite/suite_test.go
Added getter methods to the `Suite` type for both `*assert.Assertions` and `*require.Assertions`.  This allows the following:
```go
func (ste *SomeSuite) TestSomething() {
someVar, err := someFuncWithErrors()
ste.Require().NoError(err)
ste.Equal(expectedVar, someVar)
}
type RequireSuite struct {
Suite
*require.Assertions
}
func (ste *RequireSuite) SetT(t *testing.T) {
ste.Assertions = require.New(t)
ste.Suite.SetT(t)
}
func (ste *RequireSuite) TestSomething() {
someVar, err := someFuncWithErrors()
ste.NoError(err)
ste.Assert().Equal(expectedVar, someVar)
}
```
> Add getters for *assert.Assertions and *require.Assertions

- assert/assertions.go
- assert/assertions_test.go
`ObjectsAreEqual` using `ConvertibleTo` causes the `ObjectsAreEqual` function to be asymmetrical and producing incorrect assertions.
To give a few invalid examples that this patch fixes:
* `ObjectsAreEqual(2.2, 2) == true` but `ObjectsAreEqual(2, 2.2) == false`
* `ObjectsAreEqual('x', "x") == true` but `ObjectsAreEqual("x", 'x') == false`
> Exclude `ConvertibleTo` from equality test

- assert/forward_assertions.go
- assert/forward_assertions_test.go
I noticed the new EqualValues assertion, but it was conspicuously missing from forwarding_assertions. This PR adds it.
> Forwards EqualValues assertion

- mock/mock.go
github.com/stretchr/testify/mock/mock.go:289: arg m.ExpectedCalls for printf verb %s of wrong type: []mock.Call                                                                                                                       
github.com/stretchr/testify/mock/mock.go:298: arg m.ExpectedCalls for printf verb %s of wrong type: []mock.Call
> Fix "go vet" errors for incorrect printf verb

- mock/mock.go
- mock/mock_test.go
Some methods in Go take a pointer to a struct or a map and are supposed
to set some values in the referenced argument. Using Return is not
enough to mock such methods.
We are introducing a Run method that allows setting a Call handler to
make your mock update such referenced values.
Example usage mocking a service that finds a user in a data store and
fills the values in the provided struct:
```go
m.On("Find", 1, mock.AnythingOfType(*User))
.Return(nil)
.Run(func(args mock.Arguments) {
u := args.Get(0).(*User)
u.ID = 1
u.Email = "mail@example.com"
})
```
> Allow mocking methods updating referenced structs

- mock/mock.go
- mock/mock_test.go
We cannot compare two Func arguments to check if they are equal using the
reflect package. This leads to the following misleading panic:
```go
handler := func(http.ResponseWriter, *http.Request) {}
muxMock.On("HandleFunc", "/", handler) muxMock.HandleFunc("/", handler)
// panics arguing handler != handler
```
Since we cannot fix this behaviour using reflection, this patch provides a
better panic with a meaningful workaround.
```go
handler := func(http.ResponseWriter, *http.Request) {}
muxMock.On("HandleFunc", "/", handler)
// panics recommending defining the expectatin with:
//   AnythingOfType("func(http.ResponseWriter, *http.Request)")
```
Solution following the panic's instructions:
```go
handler := func(http.ResponseWriter, *http.Request) {}
muxMock.On("HandleFunc", "/", …
```
> Address #159: Meaningful panic when expecting Func

- assert/assertions.go
- assert/assertions_test.go
Address #162: InDelta should fail when actual value is not a number.
Comparting a float with NaN is always false so the assertion would always pass.
Added a check that either the actual or expected values are NaN.
InDelta will now fail if either the actual or expected value are NaN.
> Address #162: InDelta should fail when actual value is not a number.

- mock/mock.go
There is race condition caused when a method being tested calls a mocked
method within a go routine. For example, caching might be done a go
routine and that caching might be mocked.
There is already a mutex protecting the lists on the Mock object -
however Return() appends to ExpectedCalls and findExpectedCall could
run at the same time.
> Fix race condition with ExpectedCalls

- assert/assertions.go
Will fix #116.
Stacktrace stops when it reaches a function matching `TestXxx`, `BenchmarkXxx`, or `ExampleXxx`.
Example output is:
```
--- FAIL: TestFailures-4 (0.00s)
Location:       failure_test.go:18
failure_test.go:9
failure_test.go:13
Error:          Not equal: 1 (expected)
!= 2 (actual)
FAIL
```
For the following test file:
```Go
package testify
import (
"github.com/stretchr/testify/assert"
"testing"
)
func testHelper1(t *testing.T) {
testHelper2(t)
}
func testHelper2(t *testing.T) {
assert.Equal(t, 1, 2)
}
func TestFailures(t *testing.T) {
testHelper1(t)
}
```
> Add a basic stacktrace to the assertion output

- assert/assertions.go
Minor fix. The error message on the NotNil assertion was a little odd to read previously.
> Adjust NotNil error message

- assert/http_assertions.go
Use `method` (this is what http.NewRequest and the HTTP standard in
general calls this) rather than `mode` for `"GET"`, `"POST"`, etc.
> Use "method" rather than "mode" for http tests

- assert/assertions.go
> FIX# EqualError error output swaps the actual and expected values 

- mock/mock.go
The assert.Equal called had the actual and expected values mixed up. 
This resulted in the following code
```
mockProvider.AssertNumberOfCalls(t, "GetUserToken", 1)
```
producing 
```	
Error:		Not equal: 2 (expected)
!= 1 (actual)
Messages:	Expected number of calls (1) does not match the actual number of calls (2).
```
> AssertNumberOfCalls: wrong order of arguments

- assert/assertions.go
This reverts the change introduced in https://github.com/stretchr/testify/pull/205 which changed it from being correct to being wrong.
> Fix order of params in Equal

- mock/mock.go
- mock/mock_test.go
Originally the expctations required that the return values be specified immediately after the method name and arguments, otherwise the call setup will either panic (best case) or silently modify the *previous*
call specification (worst case).
This change moves the `Return()`, `Run()`, `Once()`, etc methods onto the `Call` struct, and changes the chaining behaviour so that they modify the `Call` data directly rather than referencing the last item in the `ExpectedCalls` array.
The major externally visible change is that the methods all now return a pointer to the `Call` they're operating on, rather than a pointer to the containing `Mock` instance. This would break any code that chains multiple call setups together, so I have added an `On` method to `Call` that passes the call setup through …
> Allows mock call expectations to be defined in arbitrary order

- assert/assertions.go
- assert/assertions_test.go
The NotNil assertion had an error in its handling of typed nil values.
This change makes use of the helper function isNil (used by the Nil
assertion).  The helper function has correct handling of typed nil
values and when negated provides the expected semantics for
`assert.NotNil(t, x)`.
if x == nil {
assert.Fail(t, "nil", x)
}
edit: I messed up the code block the first time. negated assertions are tricky :wink:
> Fix NotNil assertion for typed nil values

- mock/mock.go
Error happens when running Docker unit tests using gccgo. Function names are different in gccgo and hence output from runtime.FuncForPC cannot be parsed correctly with the current code.
GCCGO 
functionPath  github_com_docker_libkv_store_mock.WatchTree.pN39_github_com_docker_libkv_store_mock.Mock
Golang
functionPath  github.com/docker/libkv/store/mock.(*Mock).WatchTree
Signed-off-by: Srini Brahmaroutu <srbrahma@us.ibm.com>
> Due to function name format differences, code fails with GCCGO

- assert/assertions.go
- assert/assertions_test.go
- assert/forward_assertions.go
- assert/forward_assertions_test.go
- require/forward_requirements.go
- require/forward_requirements_test.go
- require/requirements.go
- require/requirements_test.go
While writing an API I found myself writing a lot of copy-pasta in my tests to check whether or two JSON strings represent equivalent objects. I can't be the only person using JSON strings so hopefully others will find this useful.
All this assertion does is unmarshal a string into a slice or map of `interface{}` and leverage the Equal assertion to verify equality.
> Added assertion/requirement that checks if two JSON strings represent equivalent objects

- assert/assertions.go
reflect.DeepEqual already returns exactly what we want in both of these cases.
Tests all seem to pass except testify/require, which fails with:
```
~/gocode/src/github.com/jaguilar/testify$ go test -v ./...
require/requirements.go:275: undefined: assert.Zero
require/requirements.go:282: undefined: assert.NotZero
```
> Remove unnecessary branches.

- assert/assertions.go
- assert/assertions_test.go
Makes `assert.Contains` and `assert.NotContains` work with `map` keys.
```
assert.Contains(t, &map[interface{}]interface{}{"Foo": "Bar"}, "Foo") // passes
assert.Contains(t, &map[interface{}]interface{}{"Bar": "Foo"}, "Foo") // fails
```
This fixes #118 .
> Support map keys for Contains/NotContains assertion.

- assert/assertions.go
Previous behavior was to print the error with no delimiters:
No error is expected but got unexpected character in stream
New behavior is to print the error surrounded by quotes:
Recieved unexpected error "unexpected character in stream"
> Wrap NoError message with quote marks

- assert/assertions.go
- assert/assertions_test.go
This addresses issue #229.
Example output:
```
--- FAIL: TestSomething (0.00s)
Error Trace:    main_test.go:60
Error:          Not equal: struct { foo string }{foo:"foo"} (expected)
!= struct { foo string }{foo:"bar"} (actual)
Diff:
--- Expected
+++ Actual
@@ -1,3 +1,3 @@
(struct { foo string }) {
- foo: (string) (len=3) "foo"
+ foo: (string) (len=3) "bar"
}
```
This should help when Equal fails for big structs, maps, arrays or slices.
> Show diff of values when Equal fails

- assert/assertions.go
- assert/assertions_test.go
I get this an awful lot when doing assert.EqualValues on expected error values.
> Handle case where one object is nil and the other is not

- assert/assertions.go
The `Implements` test was just showing a string instead the name of the
object that was not implementing the interface. Now the type of the
object is shown.
Related with #234
> Show type of the object instead just "Object" string

- assert/assertions.go
- assert/forward_assertions.go
Small edits to the comments on the `Empty` and `NotEmpty` funcs. Before the change the docs look like this:
After the fix, we have proper formatting:
> fixing comments for better GoDoc formatting

- assert/assertions.go
- assert/forward_assertions.go
- require/forward_requirements.go
- require/requirements.go
Noticed a few apparent typos in the comments for false asserts/requires
> True -> False in false assertion comments

- mock/mock.go
- mock/mock_test.go
Add an ArgumentMatcher interface and MatchedBy() helper to the mock
package, enabling custom fine-grained argument matching behaviors.
This is particularly helpful when building mocks over complex argument
types where deep equality is cumbersome or can't be used. Ex, a matcher
might match over just the the URL of an argument *http.Request.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/stretchr/testify/227)
> Add custom mock argument matching

- assert/assertions.go
- assert/assertions_test.go
The standard library returns always a non-pointer Time type.
Thanks for merging!
> Add check for empty time.Time struct (non pointer)

- assert/assertion_forward.go
- assert/assertions.go
- mock/mock.go
- require/require.go
- require/require_forward.go
Fix breaking change where we removed FailNow. Note FailNow is also exported in `assert` to keep symmetry between `assert` and `require`.
It's still a small breaking change since FailNow now returns a bool like the rest of the functions. However that should be compatible with all existing code bases since.
> Add FailNow back

- assert/assertions.go
- assert/assertions_test.go
Implemented new InEpsilon by calculating the relative error and
comparing it to the expected epsilon rather than calculating the
acceptable margin and using InDelta.
While doing so we got rid of the false failure when the actual value
was zero.
> Fixes #257 - InEpsilon works when actual == 0

- _codegen/main.go
- assert/assertions.go
- http/doc.go
- http/test_response_writer.go
- http/test_round_tripper.go
- mock/doc.go
- mock/mock.go
- mock/mock_test.go
- require/doc.go
- require/forward_requirements.go
- require/requirements.go
- suite/doc.go
Most lints are fixed except two:
- `assert.AnError` is kept unrenamed to keep changes backwards compatible.
- mock.argumentMatcher is unexported for the time being.
We've also changed the comments in the `http` package to be more aggressive with the deprecation warnings.
Finally we have unexported FailNower. This is a breaking change but since we released FailNower a couple of days ago it should be OK.
> Fix golint warnings

- mock/mock.go
Fix a tiny typo found while browsing go documentation.
> Fix a typo

- Godeps/Godeps.json
- vendor/github.com/davecgh/go-spew/spew/bypass.go
- vendor/github.com/davecgh/go-spew/spew/dump.go
https://github.com/AlekSi/0xb01dfacedebac1e
https://github.com/golang/go/issues/14631
https://github.com/davecgh/go-spew/commit/5215b55f46b2b919f50a1df0eaa5886afe4e3b3d
> Update vendored go-spew to fix crash on OS X.

- mock/mock.go
- mock/mock_test.go
This pull request addresses issue #293 and adds documentation warnings about
the posibility of false results for `AssertCalled` and `AssertNotCalled` when
used with pointer values.
> Fixing isse #293

- assert/assertions.go
- assert/assertions_test.go
Fix for [this issue](https://github.com/stretchr/testify/issues/347). `diff()` would not pass the go race detector, because it writes to the spew global config with no synchronization. This is easy to see when using assertions that result in non-empty diffs in tests using `t.Parallel()`. The config member assignment has been moved to the assert package's `init()` function. There are no other code paths that write to the spew config, so this should be isolated to the `diff()` function.
Unfortunately, one cannot write a test to ensure the absence of data races, since the go `race` package has no public API, so the simplest way to check is by running `go test -race path/to/assert`
> Fix #347 - Diff data race

- assert/assertions.go
While %+v shouldn't significantly change the formatting of most errors, it prints a stacktrace for errors that have been created or wrapped with pkgs/errors, which is extremely helpful for debugging.
> Changing format of NoError output to make use of errors

- assert/assertions.go
- assert/http_assertions.go
Fail and HTTPBodyNotContains expected that Fail formats messages.
> fix assertion message formatting

- mock/mock.go
- mock/mock_test.go
Fixes #342
It also logs a depreation warning.
> AssertExpectationsForObjects takes *Mock

- mock/mock.go
I use this library a lot, but even still I find the output generated when the expected arguments don't match to be incredibly difficult to use when you are dealing with non-trivial values like structs.
This PR adds one more section to the output, it will find the first argument that has any differences and print a diff. (logic lifted directly from the `assert` package) This goes a long way in making it easier to quickly identify differences and iterate.
> Mock: Add diff to output when no exact match found

- assert/assertions.go
- assert/assertions_test.go
Resolves #155.
This change causes type names to be printed when the failure message would otherwise be ambiguous. Specifically, it addresses equality assertions on numeric values of unlike types.
_Before:_
```go
assert.Equal(t, int64(123), int32(123))
//
// Not equal: 123 (expected)
//       != 123 (actual)
```
_After:_
```go
assert.Equal(t, int64(123), int32(123))
//
// Not equal: int64(123) (expected)
//      != int32(123) (actual)
```
> Clarify assert.Equal failure message given mismatched numeric types

- assert/assertion_forward.go
- assert/assertions.go
- NoError prints the error message on the next line, unquoted, which makes multiline error messages much clearer.  Sample of an error message which includes a multiline stacktrace:
Error:  Received unexpected error:
Hi!
/Volumes/Pouch/Users/russegan/dev/go/src/gitlab.protectv.local/ncryptify/client.git/client_test.go:27 (0x75c8c)
TestNew: assert.NoError(merry.New("Hi!"), "with message")
/usr/local/Cellar/go/1.7rc1/libexec/src/testing/testing.go:610 (0x70a01)
tRunner: fn(t)
/usr/local/Cellar/go/1.7rc1/libexec/src/runtime/asm_amd64.s:2086 (0x5d131)
goexit: BYTE	$0x90	// NOP
Messages:	with message
- Error,NoError,and EqualError now don’t inline the user’s extra messages.  user’s messages are printed in the “Messages:” section, as with all other assertions.
- EqualError now avoids isNil(), …
> Clearer messages

- Godeps/Godeps.json
- assert/assertions.go
- mock/mock.go
- vendor/github.com/davecgh/go-spew/spew/config.go
- vendor/github.com/davecgh/go-spew/spew/dump.go
When diffing with spew, use a format that doesn't include pointer addresses (which generate false negatives).
This updates go-spew to 04cdfd42973bb9c8589fd6a731800cf222fde1a9.
This fixes #317.
> When diffing with spew, use a format that doesn't include pointer addresses

- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
Clarify that pointer equality is determined by equality of values
rather than memory address.
Fixes #358
> Add comments for Equal and NotEqual to clarify pointer comparison

- assert/assertions.go
- assert/assertions_test.go
I'm not sure why this check is needed. It seems worthwhile to print the
type any time the types aren't equal. Closes #366.
> Remove isNumericType check

- assert/assertions.go
- assert/assertions_test.go
Previous implementation depended on tab alignment. This worked
when the output was not prepended with anything, but would break
if the output was prepended with further spaces (which can occur
in environments like IntelliJ test runners). This commit fixes it
so that the output is always aligned logically.
Fixes #83
> Ensure that assert.Fail properly align its output

- .travis.yml
Some dependencies no longer support go <= 1.3.
github.com/davecgh/go-spew/spew and github.com/stretchr/objx depend on
the "bytes" package, and github.com/pmezard/go-difflib/difflib depends
on the "bufio" package.
This change removes them from tested platforms in travis. It may make
sense to explicitly doc the lack of support elsewhere.
> travis: rm broken go releases

- mock/mock.go
Pre-diff:
```
panic: runtime error: index out of range
```
Post-diff:
```
panic:
mock: Unexpected Method Call
-----------------------------
MyFunction(string,string,string)
0: string,
1: string,
2: string
The closest call I have is:
MyFunction(string,string)
0: "mock.Anything"
1: "mock.Anything"
Provided 3 arguments, mocked for 2 arguments
```
> Check number of provided arguments vs mocked

- mock/mock.go
- mock/mock_test.go
Current Mock.Called(args...) records a method call, but the method name is the calling method. This limits a very useful use case. We are working on a library, where user could register function with a name. Then those registered functions could be invoked by name from some workflow code. The library is using reflect to get the function and passing in arguments to those registered functions. We don't know the function signature at our library's compile time. In code, it is conceptually like:
lib.Register("foo", func(...) {...})
lib.Register("bar", func(...) {...})
Then, the workflow code is something conceptually like:
result1 := lib.Invoke("foo", args...)
result2 := lib.Invoke("bar", args...)
processResult(result1, result2).
Now, we want our test suite to be able to test those workflow …
> add mock.MethodCalled(methodName, args...)

- assert/assertions.go
- assert/assertions_test.go
In some tests we compare ~1M byte slices with testify library, but since it uses `reflect.DeepEqual` this operation is very slow.
This PR adds a `[]byte` as a special case for `ObjectsAreEqual` and uses `bytes.Equal` to make comparison faster.
Benchmark results:
```
benchmark                 old ns/op     new ns/op     delta
BenchmarkBytesEqual-4     695795        261           -99.96%
```
> Compare bytes with bytes.Equal instead of reflect.DeepEqual

- README.md
- mock/mock.go
- mock/mock_test.go
Added assertions that work with the [goconvey](https://github.com/smartystreets/goconvey) testing framework.
See example test [here](https://github.com/kingofsouth/mockery/blob/convey-tests-for-testify/convey/convey_test.go#L34-L71)
> Added goconvey style assertions to the mock package

- mock/mock.go
This mainly serves to make code-completion better in IDEs that automatically create the function signature.
Feel free to close this PR if you disagree in anyway. atom + go-plus, will default automation to expand to:
```go
call.Run(func(arg1 mock.Arguments) {		
})
```
With this change it'll instead be:
```go
call.Run(func(args mock.Arguments) {		
})
```
> nit: Provide argument name `args` in function signature

- mock/mock.go
When `len(actual) > len(expected)`, this for loop would cause a panic.
Alternative to this implementation, there could be a check for
`if len(actual) != len(expected)`, but generating a meaningful message
describing that is already provided by `diff()`. So we defer to diff in
every case.
Fixes #393
> diffArguments: remove unnecessary range-for

- assert/assertions.go
Noticed the formatting in `assertions.go` was a little off, so cleaned it up.
> Fix formatting by running go fmt

- mock/mock_test.go
I have added a test case for a function with a mix of normal and variadic arguments. For example:
```go
TheExampleMethodMixedVariadic(a int, b ...int) error
```
At first I thought there was a bug in the library in such case as I was getting a weird panic in my code so I wrote this test just to make sure it works as expected.
Later I found out the bug was on my side and `testify` works correctly.
But it might be useful to have this extra test upstream anyways :)
> Added extra unit test for function with mixed variadic arguments.

- assert/assertions.go
This doesn't normally occur with `go test` which includes absolute paths, but when using `-trimpath` it's possible for the caller's file to simply be `my_test.go`. This might happen with some third-party build tools, e.g. https://github.com/thought-machine/please.
It's not easy to add a test on this without moving the code around. I'm happy to refactor a little if you'd like one though.
> Check length of path before trying to index directory.

- assert/assertions.go
Simple change coming here.
`msgAndArgs` is not being forwarded properly to `InDelta` from inside `InDeltaSlice`. This fixes this, which enables you to see what happened when `InDeltaSlice` failed to assert.
> Add msgAndArgs pass forward to InDelta from InDeltaSlice

- assert/assertions.go
Correct the usage of `assert.Equal` in the Error and NoError usage
examples, which had reversed the expected and actual arguments.
> fix(docs): correct Error usage examples

- README.md
- mock/mock.go
- mock/mock_test.go
Reverts:
- #417: bug was already fixed in another PR and code was unformatted
- #430: added exported functions had confusing names and code was unformatted
- #439: exported an internal method
@DAddYE FYI
> Revert PRs with

- assert/assertions.go
- assert/assertions_test.go
Currently it isn't possible to test if a list is a (perfect) subset of another list. On top of that it is also not possible to see if a list is equal to another list when the order is not known.
This PR makes all of this possible.
> add Subset and NotSubset assertions

- assert/http_assertions.go
- assert/http_assertions_test.go
It resolves #379 by failing tests when assertion is false or is unable to construct HTTP request.
> HTTP code status assertions now fail tests

- suite/suite.go
- suite/suite_test.go
This removes dependencies on Go Testing Internals and
also enables test methods within a suite to have subtests.
As things are now (screenshots from Gogland):
After my diff, subtests properly nest under the suite (meaning you could easily run the suite multiple times with different params and results are nicely attributed to the suite rather than just tacked on to the list):
Fixes #346 
Note: This currently breaks the logging capture part of the suite tests since Go1.7 now rolls up test output to parent T. I wanted to discuss best way to fix that. I tried to figure out how to access the rolled up test output in the parent T but I don't think it's possible even with reflection due to it being unexported. The solution I'm considering now would be to invoke go test directly via "os/exec" and …
> Use Go 1.7 subtests so suites can properly nest

- _codegen/main.go
- assert/assertion_format.go
- assert/assertion_format.go.tmpl
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- assert/forward_assertions.go
- require/forward_requirements.go
- require/require.go
- require/require_forward.go
- require/requirements.go
Related to #339
In Go 1.7, the govet will complain with the following code:
``` go
assert.Error(t, err, "test %d", i)
```
The complain is:
```
no formatting directive in Error call
```
The cause being the fact that `Error`'s signature ends with
`msgAndArgs ...interface{}` instead of `msg string, args ...interface{}`.
In this PR we add format assertions like `Equalf` and `Errorf`.
In a v2 of testify we would remove `msgAndArgs` from all the assertions and
have people use the format assertions if they want to customise the error.
> Add `assertion`f assertions like Errorf and Equalf

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
It resolves #286 by providing a simple validation function for Equal/NotEqual assertions. I have no idea how to test error messages produced by go testing framework, so I moved part of the logic to a helper function.
> Simple validation of Equal/NotEqual assertion arguments

- mock/mock.go
- mock/mock_test.go
This is a second try to address issue https://github.com/stretchr/testify/issues/437
The original PR https://github.com/stretchr/testify/pull/439 was merged then reverted.
This PR avoid exposing internal function which is the reason pull #439 was reverted.
Really hope this could be merged as this would support a very useful use case.
Please put comments if you see anything that needs to be changed for this PR to be merged.
Thanks.
> add MethodCalled to the mock

- assert/assertions.go
In a similar stroke to #475, the long tail of yoda ordering strikes again.
> Fix InDelta expected nan check message

- assert/assertions.go
reflect.Value.Len() can cover more types, per godoc:
> Len returns v's length. It panics if v's Kind is not Array, Chan, Map, Slice, or String.
> Issue #469 fix

- mock/mock.go
- mock/mock_test.go
This change fixes a race condition I discovered when a multithreaded test in a service I work on failed under -race.  The included test case simulates that failure (concurrent mutation of a Call with invocations on the mock).  The test will fail with a data race if run under the race detector; the new locking ensures that call fields are not accessed without the protection of the parent mutex.
> Fix unprotected call fields access in MethodCalled()

- assert/assertions.go
- assert/assertions_test.go
I had some issues using the `Empty` assertion with a custom string type: let's say I define `type TString string`, then `assert.Empty(t, TString(""))` would fail. The `Empty` would also not work against empty custom structs. 
Fixed by doing a `reflect.DeepEqual` against the type's `reflect.Zero`.
> generalize isEmpty

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
Based on https://github.com/stretchr/testify/pull/511
Adds `InDeltaMapValues` assertion, aligned with `InDeltaSlice`.
`InDeltaMapValuesf` is the same as `InDelta`, but it compares all values between two maps. Both maps must have exactly the same keys.
> Implement delta comparison for map values

- assert/assertions.go
- assert/assertions_test.go
I found an indentation of the actual value quite useful for comparison.
My usecase for this change was the equal assertion on two urls with parameters where a parameter was missing in one of both urls.
An indentation helped a lot in this case.
> indent actual value for better comparison with expected value

- assert/assertions.go
From: https://github.com/stretchr/testify/pull/472
> In case of a test failure, the test name will be logged to the output
> with makes debugging easier, specially in case of table driven tests.
New pr to cleanup history.
> fail: add test name for logged output

- mock/mock.go
- mock/mock_test.go
After was using call.WaitUntil(time.After(duration)),
`ch := time.After(duration)` returns a channel with the timer immediately started.
> Fixing After(duration) to wait during method call

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/http_assertions.go
- require/require.go
- require/require_forward.go
HTTP assertions were missing the trailing `msgAndArgs ...interface{}`,
making it inconsistent with the rest of the assertions and resulting in
incorrect `*f` wrappers.
Fixes #528
> Fix HTTP assertions to be consistent with the rest

- .travis.yml
From now on, we will support the last 3 major Go versions, which covers
at least one year and a half of Go versions.
> Drop old Go versions from tests

- .travis.yml
Until we drop support of Go < 1.9, skip vendored packages manually.
Once Go 1.11 is released, we would be able to just use ./...
> Skip vendored packages from tests

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- require/require.go
- require/require_forward.go
Fixes #525
Return information was propagated to the docs from other wrapper
functions which return nothing.
> Remove returns info from assertion docs

- mock/mock.go
it's very confusing to see a list of all PASS msgs while the actual assert failed.
> Print missing FAIL during AssertExpectation

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- require/require.go
- require/require_forward.go
As per https://github.com/stretchr/testify/pull/549 from @larsxschneider
> Docs: Remove superfluous parenthesis

- mock/mock.go
- mock/mock_test.go
This really help to figure out which calls haven't been called yet.
result looks like this:
```
mock.go:419: PASS:	GetBlock(chainhash.Hash)
mock.go:419: PASS:	GetBlock(chainhash.Hash)
mock.go:419: PASS:	GetBlock(chainhash.Hash)
mock.go:412: FAIL:	GetBlock(chainhash.Hash)
at: [package_test.go:1918]
```
> Store CallerInfo when On() is called and print during AssertExpectations

- assert/assertion_format.go
- assert/assertion_format.go.tmpl
- assert/assertion_forward.go
- assert/assertion_forward.go.tmpl
- assert/assertions.go
- assert/assertions_test.go
- assert/http_assertions.go
- require/require.go
- require/require.go.tmpl
- require/require_forward.go
- require/require_forward.go.tmpl
- require/requirements.go
Use Go 1.9 t.Helper() to remove testify from the output of the tests and
stop using `\r` to try to overwrite the output.
This means in Go 1.7 and Go 1.8 testify will appear as failing the test.
> Fix vim-go integration and other editors

- mock/mock.go
- mock/mock_test.go
Adding log for assertExpectationsForObjects mock failure.
```
func AssertExpectationsForObjects(t TestingT, testObjects ...interface{}) bool {
```
fixes #507
> Adding logging when mock assertions fails

- .travis.yml
- README.md
Since go 1.10 go versions must be set as strings
[Building a Go Project \- Travis CI](https://docs.travis-ci.com/user/languages/go/#What-This-Guide-Covers)
> Note that, in order to choose Go 1.10, you must use go: "1.10" (a string), not go: 1.10 (a float). Using a float results in the use of Go 1.1.
> Bump go version to 1.10

- mock/mock.go
* Clearer messages for AssertCalled and AssertNotCalled
* Call `t.Helper` on assertion helpers
Fixes #398
> Improve mock assertion errors

- assert/http_assertions.go
- assert/http_assertions_test.go
Removes the unwanted `?` as mentioned in #522
> Adding url.Values to request RawQuery, fixes 522

- mock/mock.go
- mock/mock_test.go
when expected method call wasn't found, but there's a closest method display the diff during panic.
especially this helps for argumentMatcher. closes #556
> Display arguments Diff during panic

- mock/mock.go
- mock/mock_test.go
This makes is possible to fail the test instead of panicing in case that the method was called with unexpected arguments.
Instead of #569
Fixes #489
>  Add T object and Test method to Mock

- README.md
This adds an example to the docs that uses a placeholder in the On arguments
> Add placeholder example to docs

- assert/assertions.go
- assert/assertions_test.go
- require/requirements.go
- require/requirements_test.go
Basically this PR is just adding these function aliases:
```
type ValuesChecker func(TestingT, interface{}, interface{}, ...interface{}) bool
type ValueChecker func(TestingT, interface{}, ...interface{}) bool
type BoolChecker func(TestingT, bool, ...interface{}) bool
type ErrorChecker func(TestingT, error, ...interface{}) bool
```
I have added tests and Examples so there will example usage in the docs.
I find myself frequently using table driven tests to test various edge cases of my functions, but I generally want to test both the positive and negative cases.
Lets say I have a trival function `func MyFunc(input string) error`, typically the data tests would look something like this (without `testify`):
```
tests := []struct {
name    string
arg     string
wantErr bool
}{
{"good test", …
```
> add a few function types to assist table driven tests

- assert/assertions.go
- assert/assertions_test.go
This PR brings diff support to strings, which looks something like this:
Which without diff support, would look like this: 
I think this could close https://github.com/stretchr/testify/issues/518 https://github.com/stretchr/testify/issues/589
> RFC: support diff display for string variables

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/http_assertions.go
- require/require.go
- require/require_forward.go
The doc comments were missing the method in two cases.
Q: I might be missing something, but does the `msgAndArgs` business work for `http_assertions`? I don't see those being used (or passed to some other `assert.*` function) in the function bodies of the `HTTP...` methods. 🤔
> fix docs: http assertions

- mock/mock.go
- mock/mock_test.go
Some values will panic when fmt.Sprintf'd with `%s`, e.g. https://godoc.org/github.com/boltdb/bolt#Tx.  
When mocking a method that has such a value in its arguments, the program will panic due to Argument.Diff attempting to print the interface{} type with `%s`.
Normally the compiler will prevent using such a value in a formatter but the code bypasses this by operating on `interface{}`.
This PR changes the formatter to use `(%T=%v)`. `%T` is used to mimic the previous behaviour which generated outputs like `%!s(int=123)`.
> Format matched arguments with %v to avoid panic

- assert/assertions.go
- require/requirements.go
Hey testify friends
This is a small change to fix a mismatch between a comment and the exported function name it describes.
> update comment to match function name

- LICENSE
- README.md
The reason is that since the name of the license is not stated
explicitly and the license text differed very slightly I had to perform
a diff to ensure it actually is MIT licensed. Also GitHub does not
detect the license for this project currently (probably for the same
reason).
Changes:
* Remove the line 'Please consider promoting this project...' that is
not part of the MIT license
* Use the same formatting as choosealicense.com
* Explicitly state 'MIT License'
* Update the copyright year
> Update the LICENSE to match the 'standard' MIT license file

- assert/assertions.go
- assert/assertions_test.go
Currently, if `msgAndArgs` contains exactly one element, it's expected to be a `string` -- and if it's not, the framework panics, which makes it hard to debug the actual test failure. So, if the object passed is not a string, then print it using the `%+v` modifier.
This will make life slightly more convenient for clients. It doesn't break existing programs in any way.
> Support arbitrary objects as the sole element in msgAndArgs

- suite/suite.go
- suite/suite_test.go
PR implements feature suggested in https://github.com/stretchr/testify/issues/695 (don't panic in tests, but gracefully recover, mark test as failed and run other tests)
> Recover panic in suite

- .travis.yml
- go.mod
- go.sum
What
===
Add `go.mod` and `go.sum`, using `Go 1.11`.
Why
===
Now that golang/go#24301 has been accepted, lets start using go.mod files
alongside Godep, and keep the two in sync.
Notes
===
There are no changes required to testify to support go.mod. The files were
generated by running `go build` and `go mod tidy.
Merging
===
This PR is intended to be merged after #659 which adds Go1.11 to the list of
supported builds.
> Add go.mod and go.modverify

- mock/mock.go
> Fix typo ("PASS" -> "FAIL")

- mock/mock.go
- mock/mock_test.go
Fixes #705 
Go tip contains following commmit, that inlines function with single
call bodies.
https://github.com/golang/go/commit/13baf4b2cd34dfb41c570e35b48ec287713f4d7f
`(*Call).On()` is the exact target for the improvement in Go repo. Due to
the inlining, assert.CallerInfo() can't not detect the file and line
number of the call to `(*Mock).On()` from `(*Call).On()`. Thus, the test
fails.
Adding the compiler directive `go:noinline` prevent this effect and make
mock package works with go tip as before.
> Preserve stack frame for mock parent method call

- README.md
I noticed the Installation section of the readme was a little outdated.
> Update readme to deprecate http and include available packages

- assert/assertions.go
The aim of the PR is just small refactoring:
- Put calculation of `elementValue := reflect.ValueOf(element)` direct in place where it is required.
- Calculate `listKind := reflect.TypeOf(list).Kind()` only one time.
> refactor includeElement method

- suite/suite.go
- suite/suite_test.go
When suite setup is long, the necessity to wait for all suite setups for testing one single method of one of suites bothers a lot. Here's a little fix of that behavior.
> Don't setup suite if no methods satisfy filter

- require/require.go
- require/require.go.tmpl
In order for line numbers to be displayed correctly when printing errors from a require.* function, h.Helper() needs to be called before the assert.* test. Otherwise all line numbers will point to require.go
> Helper is called before assert function in require.* functions

- assert/assertions.go
- assert/assertions_test.go
Adds pointer comparison function `Same` to `assert` package, based on discussion in #597.
Both arguments must be pointer variables. Pointer variable sameness is determined based on the equality of both type and value.
> add ptr comparison func `Same` to assert pkg

- assert/assertion_format.go
- assert/assertion_forward.go
- require/require.go
- require/require_forward.go
Run `go generate ...` from top of testify tree. This brings in wappers
for Greater, GreaterOrEqual, Less, LessOrEqual and Same.
> assert, require: Regenerate

- README.md
- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertion_order.go
- require/require.go
- require/require_forward.go
In documentation change this and other similar entries:
```
- LessOrEqual asserts that the first element in greater or equal than the second
+ LessOrEqual asserts that the first element is less than or equal to the second 
```
In test output for `LessOrEqual(t, 2, 1)` change this and similar:
```
-                Error:          "%!s(int=2)" is not less or equal than "%!s(int=1)"
+                Error:          "2" is not less than or equal to "1"
```
> Fix docs and output for LessOrEqual and friends

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
Introducing `assert.Eventually`, to verify if given condition will be met in given time.
Such method is useful for testing asynchronous actions, for example in integration tests we can use `assert.Eventually` to verify that condition is met in given time, instead of using `time.Sleep()` with predefined and always too long wait duration - this way tests complete faster.
Example usage? Send an event to some event bus, then wait for condition to be satisfied in given time (for example wait that HTTP endpoint will return something based on that event consumption)
Other testing tools contain similar methods, for example: http://spockframework.org/spock/javadoc/1.2/spock/util/concurrent/PollingConditions.html
Please share if you find it as valuable as I do.
> Introduce Eventually assertion.

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- assert/forward_assertions_test.go
- go.mod
- go.sum
- require/forward_requirements_test.go
- require/require.go
- require/require_forward.go
- require/requirements_test.go
Like JSONEq, I added YAMLEq to check whether YAML strings are equivalent.
Fixes https://github.com/stretchr/testify/issues/743
> Add YAMLEq to assert that two YAML strings are equivalent

- mock/mock.go
- mock/mock_test.go
the error message is confusing for over-repeating calls.
test code:
```Go
package tests
import (
"testing"
"github.com/stretchr/testify/mock"
)
type myMock struct {
mock.Mock
}
func (m *myMock) DoSomething(num int) error {
return m.Called(num).Error(0)
}
func Test_call(t *testing.T) {
var tMock = new(myMock)
tMock.On("DoSomething", 0).Return(nil).Once()
tMock.DoSomething(0)
tMock.DoSomething(0)
tMock.AssertExpectations(t)
}
```
Current test fail message:
```
mock: Unexpected Method Call
-----------------------------
DoSomething(int)
0: 0
The closest call I have is: 
DoSomething(int)
0: 0
Diff: No differences.
goroutine 19 [running]:
testing.tRunner.func1(0xc000120100)
/usr/local/go/src/testing/testing.go:792 +0x387
panic(0x13209a0, 0xc000095130)
/usr/local/go/src/runtime/panic.go:513 …
```
> Improve  error message for over-repeating calls

- assert/assertions.go
- assert/assertions_test.go
Fixes #805
Fixes #835 
/cc @gmiejski @georgelesica-wf
> Fix panic for Eventually functions

- .travis.gogenerate.sh
- .travis.govet.sh
- .travis.yml
- README.md
- _codegen/.gitignore
- _codegen/go.mod
- _codegen/go.sum
- _codegen/main.go
- assert/assertions.go
- assert/forward_assertions.go
- require/forward_requirements.go
- require/requirements.go
- suite/suite.go
- suite/suite_test.go
Fix two issues with codegen that cause it not to work with Go Modules.
1. Changed `SrcRoot` and `ImportPath` to `Dir`. When parsing the code files the package SrcRoot and ImportPath were being joined which assumes the package is hosted inside a GOPATH src directory. Using those two fields is unnecessary because Dir tells us where the package lives.
2. When checking the types in the source files the default importer is being used. Unfortunately the default importer has not been updated to work with Go Modules and it only looks in the GOPATH for imports. Luckily the Go team were convinced to backport some logic from the newer go/packages package to go/build, and we can make use of the go/build importer which supports Go Modules.
In the future codegen should be rewritten to use go/packages …
> Fix go generate for Go Modules

- assert/assertions.go
- assert/assertions_test.go
Time Duration mismatch from nanoseconds (int64) to readable format.
Fixes #626.
> Time duration diff format

- .travis.gofmt.sh
* Check if we have mismatching `go generate ./...` output on builds
Fixes #874
> Check go generate on builds

- .travis.yml
* Changed the latest Go version of the Travis build to be master instead of dev
> Use latest Go master instead of dev

- assert/assertions.go
Fixes #837
This PR is a rebased version of #838
> assert.Eventually: fail the testcase if condition is not met

- mock/mock.go
- mock/mock_test.go
Like [`assert.IsType(...)`](https://godoc.org/github.com/stretchr/testify/assert#IsType), `mock.IsType` is a type-safe way to check that the type of an argument is the expected type. This is an alternative to using the name of a type with `AnythingOfType`.
> IsType: A type-safe way of checking argument type

- mock/mock.go
- mock/mock_test.go
Added function 'IsMethodCallable', which checking that the method can be called.
```
if !userService.IsMethodCallable(t, "FindByID", userID) {
return nil
}
args := s.MethodCalled(t, "FindByUserID", userID)
// TODO
```
> Check method callable

- assert/assertions.go
- assert/assertions_test.go
*NOTE*: this changes something that is the default behavior. I intentionally am doing this as a proposal to change that behavior because I think the new one is better. If this is a problem, we could also achieve the goal of this PR by making `spewConfig` somewhat accessible so that the user of the library can choose to `DisableMethods` themselves.
`spew`'s default formatter will call `String()` or `Error()` in structs
that implement the `fmt.Stringer` or `error` interfaces. Depending on
the implementation of those, the diff can become quite useless to read
(see the example struct I used for the test case in this commit).
This changes `spew`'s configuration to `DisableMethods` so that it will
always use it's own pretty printer. This makes testing structs less
surprising and generally more …
> Disable using Stringer/error interfaces for diffing

- assert/assertions.go
- assert/assertions_test.go
If you were comparing values which when formatted were longer than about 64k then the actual, expected and diff messages were not printed to the console.
> fix: error diff was not being show for large values

- assert/assertions.go
- mock/mock.go
- Direct boolean comparisons
- Don't use Sprintf when we can use the String() function
> Simplify code

- assert/assertions_test.go
err can't ever be not nil here, unless the Go language specs are changing.
> Fixed tautological errors

- http/test_round_tripper.go
- package_test.go
- suite/suite.go
- suite/suite_test.go
Fixed formatting and import order.
> Format code with goimports

- assert/assertion_order.go
- assert/assertion_order_test.go
Refactoring of the assertion order functionality:
- Using constants `greater`, `equal`, `less` instead of `-1`, `0`, `1`. Now the code become more readable.
- Unify working with comparing results. There was almost the same copy-pasted code for `Greater`, `GreaterOrEqual`, `Less`, `LessOrEqual` functions. Now these call one function with all common logic. It could help to change behavior for all of them in future.
Linked issue https://github.com/stretchr/testify/issues/903 .
> refactoring of assertion_order

- assert/assertions.go
- assert/assertions_test.go
It is not very helpful to print that the lengths differ when an
assertion fails, since that does not reveal what the cause of the issue
might be.
Let's print which elements are extra in each list, that should convey
the relevant information to the user. Also use spew to format the
objects, similar to what Equal does, to make the output more readable.
> Print more details in ElementsMatch

- assert/assertions.go
- assert/assertions_test.go
> Make InEpsilon fail when given a NaN

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/http_assertions.go
- assert/http_assertions_test.go
- require/require.go
- require/require_forward.go
@glesica @boyan-soubachov  Please consider this PR for merging.
**Motivation**
The current set of HTTP asserts do not cover the full range of status codes. This addition would allow a user to test for a specific status code.
As such it would cover the full range of status codes, including for example: `http.StatusSwitchingProtocols`.
**Example usage**
`assert.HTTPStatusCode(t, myHandler, "GET", "/", nil, http.StatusSwitchingProtocols)`
**Whether you intend to add / change behaviour or fix a bug**
Adds behaviour.
**Additionally**
- Would also close #824 
- Includes test
- Tests ran successfully
> Add HTTPStatusCode assertion

- suite/suite.go
Add a warning message when no tests are run within a suite. Before this change it would just report passed with no indication that nothing was actually run.
Added a check that there are tests to actually run and a warning to testing.Log if there are not
See issue 862. It is easy to assume that all your tests have passed when in fact you didn't run any because of perhaps a typo in your regex.
Closes #862
> Add warning in log when no tests are run within a suite

- mock/mock.go
- mock/mock_test.go
Panic mocks a function call that panics with the specified message
Usage:
c := mockedService.
On("TheExampleMethod", "A", "B", true).
Panic("panic message for example method")
The above mocked service would panic with message `panic message for example method`
> panic: add .Panic() to mock.Call

- assert/assertions.go
- go.mod
- go.sum
I'd like to upgrade to testify v1.4.0, but I'm using `gopkg.in/yaml.v3`, and testify uses `v2` - I'd rather not pull in both, so I thought it would make sense to upgrade.
I also re-vendored since I noticed it was out of date. And I updated the `Gopkg.lock` with `dep ensure`, though maybe it would make sense to drop that since this repo is using go modules now?
Signed-off-by: Dave Henderson <dhenderson@gmail.com>
> Update dependency to gopkg.in/yaml.v3

- mock/mock.go
- mock/mock_test.go
Fixes a regression in `testify/mock`.
Handle nil in Arguments.String() by employing fmt.Sprint().
A regression introduced while replacing `fmt.Sprint()` with `reflect.TypeOf(arg)` in `Arguments.String()`: `reflect.TypeOf(nil)` returns `nil` which is its documented behaviour. A null pointer dereference is what follows.
A unit test case added.
Closes #936.
> mock: callString to handle nil nicely

- assert/assertions.go
- assert/assertions_test.go
InDelta and InEpsilon assertions on uint values would fail with
the error "Parameters must be numerical".
> Support uint in InDelta and InEpsilon

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/http_assertions.go
- assert/http_assertions_test.go
- require/require.go
- require/require_forward.go
Issue  #925
Http Assertions does not allow the creation of a body
* Added body argument in HTTPBodyContains and HTTPBodyNotContains 
* in tests added httpPostHandler which reads request body and writes to response
* In HTTPBody checking if there are url params , otherwise not adding to url
#925
> allow body for HTTPBodyContains and HTTPBodyNotContains for POST

- assert/assertions.go
- assert/assertions_test.go
Move some calls to `testing.Helper()` to reduce overhead.
Move call to `Helper()` after the check in various straightforward `assert` cases.
~Short-circuit `require.NoError()` and `require.NoErrorf()` so they do not call `Helper()` when no error is found.~ - deferred till another time
`Helper()` in the standard Go runtime fetches a stack trace from the runtime, so is slow for calls that are made many times.  However, `Helper()` only makes a difference if the call throws an error, so we can avoid that overhead in many cases which are otherwise cheap.
#766 (not a full fix)
> Optimise runtime for passing tests

- .travis.yml
- suite/suite.go
- suite/suite_test.go
Fixes a deadlock when there is a failing test in a suite when run with failfast
This commit https://github.com/stretchr/testify/commit/0d3c8ce9f8c3be984ccd5d2e3438b173ea722267 attempted to fix an ordering issue with suite teardown, but introduced a deadlock when a test fails when running with failfast.
The problem is that the sync.WaitGroup was being incremented for each test which was expected to be run, but with failfast not all of those tests were actually run. Then the first test is trying to run tearDownAllSuite after itself but waiting on the sync.WaitGroup which never wakes up.
I think we can just move the tearDownAllSuite  into a defer which will run after we have run whatever tests are going to be run, without the need for a sync.WaitGroup at all.
Fixes a defect
Closes #917
> Change how tearDownAllSuite is run to aviod deadlock when running with failfast

- assert/assertion_compare.go
- assert/assertion_compare_test.go
fix format string for numbers. without this patch, we got something like
```
Error:      	"%!s(int=382)" is not less than "%!s(int=100)"
```
> assertion_compare: fix format string for numbers

- _codegen/main.go
- assert/assertion_format.go
- assert/assertion_forward.go
- require/require.go
- require/require_forward.go
Fix `CommentFormat` regular expression to resolve incorrect examples for numerous functions in `assertion_format`
Changed
`exp := regexp.MustCompile(replace + `\(((\(\)|[^)])+)\)`)`
To:
`exp := regexp.MustCompile(replace + `\(((\(\)|[^\n])+)\)`)`
Fixes examples for the following functions in `assertion_format.go`:
Greaterf, Equalf, EqualValuesf, HTTPErrorf, HTTPRedirectf, Implementsf, Lessf, NotRegexpf, Regexpf
Closes #941, #943, #927
> Fix incorrect parentheses in docstrings for some functions

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- assert/forward_assertions_test.go
- require/require.go
- require/require_forward.go
- require/requirements_test.go
This PR implements NotEqualValues(), as requested (partially) in #640
Changes consist of adding the implementation of NotEqualValues(), similar to how currently EqualValues() and NotEquals() are implemented.
When asserting that values do not equal using `NotEquals`, the assertion will already be true if types differ. This can happen easily when using numeric literals, e.g.
```
assert.NotEquals(t, 10, SomeFuncReturningUInt())
```
will hold even if the func returns 10 since the type assigned by the compiler / returned by the func differ.
Implements #640  in part.
> Issue640 add NotEqualValues()

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/http_assertions.go
- assert/http_assertions_test.go
- require/require.go
- require/require_forward.go
Reverts a breaking change that was incorrectly tagged for v1.6.0 instead of v2.0.0
Reverts https://github.com/stretchr/testify/pull/938
A breaking change was released by mistake
> Revert 'body' parameter in `HTTPBodyContains` and `HTTPBodyNotContains`

- .travis.yml
Updated the versions of Go we run on to reflect our support protocol. This is as discussed in the #testify-maintainers Slack channel
* Removed Go 1.11, 1.12 and 1.13 from the Travis build. Have kept Go 1.10 as a sentinel build in-case we break something with Go modules.
Supports the latest Go (1.14) and reduces workload by removing runs for unsupported versions.
> Update Go versions in Travis

- assert/assertions_test.go
This refactors some of the tests but does not add any new ones.
- define test cases in tables where sensible
- combine testcases for `Foo()` and `NotFoo()`, specifically there were testcases were already the same
- make some types local to funcs if not used elsewhere
- table based tests are the way to go.
As discussed in #953
> Refactor unit tests to table-driven tests

- assert/assertion_compare.go
- assert/assertion_compare_test.go
Allow comparing custom numeric types without panics. 
Prior to this commit, this would not work:
```go
type myInt int
assert.Less(t, myInt(1), myInt(2)) // panic!
```
We add some type conversions, similarly to how `ObjectsAreEqualValues`
work. This allows us to compare `myInt` to `myInt`, as well as `myInt`
to `int`.
It's a pain doing `assert.Less(t, int(myCustomIntValue), 8)` every time I want to compare numbers.
> Allow comparing custom numeric types

- .travis.yml
Remove Go 1.10 from TravisCI builds due to it being deprecated
Go 1.10 is unsupported by the Go team. It is also preventing us from adding code and fixes for features available in newer versions of Go.
> Remove Go 1.10 from Travis builds

- README.md
- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
Add assertions for `error.Is` and `error.As` functions.
Example implementation of ErrorAs and ErrorIs
See #970 
Closes #970
> Wrap Go 1.13 error functions

- assert/assertions.go
Since its a simple fix, let's just do the rebase ourselves as it were. Thanks for the original PR @quasllyte (#642)
> assert: s/rune/r/ to avoid "rune" predeclared ident shadowing #642

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertion_order.go
- assert/assertion_order_test.go
- require/require.go
- require/require_forward.go
Add assertion of collections ordering.
It could help to check collection on specific order.
```go
assert.IsIncreasing(t, []int{1, 2, 3})
```
Closes #710
> add assertion order

- README.md
On README.md, there are many examples as useful.
But I was a little worried about a test case name on Mock section.
I think test case name should contain a target method name accurately and indicate what would you want to test.
So I change two test case name on readme.
I change two test case name as below.
1. Match method name to sample method.
`func TestSomething(t *testing.T)` → `func TestDoSomething(t *testing.T)`
2. Match method name to sample method and indicate what is the different with above.
`func TestSomethingElse(t *testing.T)` → `func TestDoSomethingWithPlaceholder(t *testing.T)`
Test case name should indicate which method is targeted and what you want to test.
It's important not only production code but also sample code.
> Revise test case name on README.md of mock section

- assert/assertion_compare.go
- assert/assertion_compare_test.go
- assert/assertion_format.go
- assert/assertion_forward.go
- require/require.go
- require/require_forward.go
Adding positive/negative assertion functions
What do you think about these changes?
- Adding function `Positive` to assert that the specified element is positive
- Adding function `Negative` to assert that the specified element is negative
When we want to assert that some value is positive or negative, we test like below.
```go
func TestHoge(t *testing.T) {
assert.Greater(t, 1, 0) // want to assert positive
assert.Greater(t, 1.23, 0.0) // want to assert positive
assert.Less(t, -1, 0) // want to assert negative
assert.Less(t, -1.23, 0) // want to assert negative
}
```
By adding `Positive`/`Negative` assert functions, we can simplify it like an example usage below.
```go
func TestHoge(t *testing.T) {
assert.Positive(t, 1)
assert.Positive(t, 1.23)
assert.Negative(t, -1)
assert.Negative(t, …
```
> Add positive/negative assertion

- assert/assertions.go
The latest update to golang/protobuf (I am on v1.4.2) break the spew circular data structure detection. This means that when calling `assert.Equal(t, proto1, proto2)`, if it fails it will enter an infinite recursion.
By limiting the recursion with `MaxDepth` set to a large number (10 seems reasonable as a struct that is 10 deep will be pretty large) this means that if there is an issue with recursion (as there is with protobuf) the test will still return a failure in a reasonable time instead of just a timeout.
Adding MaxDepth to spew output.
Stop infinite loop if spew fails to detect circular recusion.
> [Fix] Limit the spew recursion

- README.md
This PR changes the godoc/badge link to point to the new pkg.go.dev site
> Updated the readme to point to pkg.dev

- assert/assertion_compare.go
- assert/assertion_compare_test.go
The file name in the failed summary shows files inside the `testify` package, instead the real testing file. E.ge
```
--- FAIL: TestCurrentCache (0.12s)
assertion_compare.go:221: 
Error Trace:    xxxx_test.go:352
Error:          Elements should be the same type
Test:           TestXXXX
Messages:       []
```
The `assertion_compare.go` is a file inside `testify` package. It should also show `xxxx_test.go:352` as the `Error Trace`.
Make functions inside `testify` package as test helpers with:
```
if h, ok := t.(tHelper); ok {
h.Helper()
}
```
With this PR, the filename and number would correctly show `xxxx_test.go:352`
> fix the output source file in test output

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- assert/forward_assertions_test.go
- require/forward_requirements_test.go
- require/require.go
- require/require_forward.go
- require/requirements_test.go
It's common practice to wrap errors, so that you do not have a transitive dependency on the error format of a third party library, but also so that you are able to exactly match you are testing a specific error case correctly.
This change adds an `ErrorContains()` method to check that both an error is reurned, and it contains a provided string.
Added `ErrorContains()` and `ErrorContainsf()`.
When I wrap errors returned from third party modules:
```go
func method(f foo, b bar) error {
if err := f(); err != nil {
return fmt.Errorf("foo failed: %w", err)
}
if err := b(); err != nil {
return fmt.Errorf("bar failed: %w", err)
}
return nil
}
```
This then forces me to write:
```go
f := func() error { return assert.AnError }
b := func() error { return nil }
err := method(f, b)
require.Error(t, …
```
> Add ErrorContains

- assert/assertions.go
- assert/assertions_test.go
Make sure time.Time comparison produces a helpful diff. closes #989
Make sure time.Time comparison produces a helpful diff
again. This partially reverses the changes in #895 for
time.Time and allows it to be easily expanded for more
types in the future if needed.
Analyzes the type when diffing, and uses a different
Spew config for time.Time
Introduce a test for diffing time.Time
See bug #989
Closes #989
> Make sure time.Time comparison produces a helpful diff. closes #989

- mock/mock.go
- mock/mock_test.go
Proposed fix for #423 and possibly #625 if it's the same issue.
See comment on Mock.String for explanation.
> Add String method to Mock to fix #423

- mock/mock.go
- mock/mock_test.go
Improve the Diff message for `mock.MatchedBy` functions taking a reference type.
The `argumentMatcher.String` method internally now uses the `reflect.Type.String` method instead of the `reflect.Type.Name` method.
Prior to this change a `mock.MatchedBy` function taking a reference type, such as a slice (`func([]int) bool`), would have the Diff presented as `... func() bool`; now the Diff will accurately be presented as `... func([]int) bool`.
N/A
> Improve mock.MatchedBy failed comparison Diff message

- assert/assertion_compare.go
- assert/assertion_compare_can_convert.go
- assert/assertion_compare_go1.17_test.go
- assert/assertion_compare_legacy.go
- assert/assertion_compare_test.go
Add support for comparing `time>Time` and custom types derived from it.  
When comparing types, see if we're comparing `time.Time`, or a custom type based on `time.Time`. If that's the case, compare their Unix timestamps, with the smallest possible resolution. 
This now allows sticking a `time.Time` into `assert.Greater` and `assert.Less`, which is nice. Time stamps have a natural ordering, so I'd expect this to work.
> assert: allow comparing time.Time

- assert/assertions.go
- assert/assertions_test.go
Previously, the function would not detect panic(nil) calls.
In didPanic, removed the anonymous function call, instead,
added named return values. Added extra test cases for the
panic(nil) call.
Closes #794.
> Fixed didPanic to now detect panic(nil).

- README.md
Rather than directly adding `1.16`, I thought better to reword to state the minimum version supported... this way the line doesn't have to get updated with every new release, but instead only when dropping support for old releases.
> Update versions supported to include `go 1.16`

- suite/suite.go
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>
we find a data race in the suit. so we think Mutex is added to the suit for solving it.
ref https://github.com/pingcap/tidb/issues/32747
```
==================
WARNING: DATA RACE
Write at 0x00c026a29588 by goroutine 117:
github.com/stretchr/testify/suite.(*Suite).SetT()
/home/prow/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:37 +0x148
github.com/pingcap/tidb/executor_test.(*infosSchemaClusterTableSuite).SetT()
<autogenerated>:1 +0x44
github.com/stretchr/testify/suite.Run.func1()
/home/prow/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:128 +0xcc
testing.tRunner()
/usr/local/go/src/testing/testing.go:1259 +0x22f
testing.(*T).Run·dwrap·21()
/usr/local/go/src/testing/testing.go:1306 +0x47
Previous read at …
```
> fix data race in the suit

- .github/workflows/main.yml
These are the latest versions listed on https://go.dev/dl/
I didn't add `1.18` as it seemed like a somewhat generic release, so beyond the scope of this PR.
> Update go versions in build matrix

- .github/workflows/main.yml
- mock/mock.go
Added Go 1.18.1, removed Go 1.15.13 from the build versions. This brings us up-to-date with the latest supported Go versions.
Add Go 1.18.1
Removed Go 1.15.13 as a build version as it's no longer supported
> Added Go 1.18.1 as a build/supported version

- mock/mock.go
- mock/mock_test.go
Regression was introduced in #1182 (released in v1.7.3) which updated the mock mutex to be a pointer and updated _most_ call sites that check this mutex to initialize if it's not yet, however the `mock.AssertExpectationsForObjects` and thus the `mockObject.AssertExpectations` did not take this into account which results in a panic. It's common to initialize mocks at the start of a test and then defer asserting expectations for the end of the test regardless of if a mock had expectations set on it or not. This happens in cases where the test mock does not set any `On()` methods or does not call `mockedObject.Test(t)` which would initialize the mutex if it's not set. Calling `mockedObject.Test(t)` is a fine workaround, but regardless this is a regression.
I added a test case that repro's …
> Fix panic in AssertExpectations for mocks without expectations

- assert/assertion_compare.go
- assert/assertion_compare_go1.17_test.go
Signed-off-by: Ryan Leung <rleungx@gmail.com>
Support comparing byte slice
Add byte slice in the `compare` function.
```
func TestByteSlice(t *testing.T) {
re := require.New(t)
objs := [][]byte{[]byte("abc"), []byte("abcd"), []byte("abcde")}
testcase := []byte("ab")
for _, obj := range objs {
re.Less(testcase, obj)
}
}
```
> Support comparing byte slice

- suite/suite.go
- suite/suite_test.go
In testify, in tests that `panic()`, `WithStats` is not correctly ended. See #1189 for details
probably not the prettiest fix but it works. Let me know what you think
Looks like a bug
Closes #1189
> fix(suite) correctly set stats on test panic

- mock/mock.go
- mock/mock_test.go
If an argumentMatcher function panics and AssertExpectations is deferred then the test would deadlock.
* Capture panics from argumentMatcher functions and show them to the user as a difference
It was reported that when AssertExpectations() is deferred and an argumentMatcher function panics, that the test will deadlock.
Example from linked issue:
```go
import (
"testing"
"github.com/stretchr/testify/mock"
)
type Mock struct {
mock.Mock
}
func (_m *Mock) F() {
_m.Called()
}
func TestMatcherPanic(t *testing.T) {
m := &Mock{}
defer m.AssertExpectations(t)
matcher := mock.MatchedBy(func(_ interface{}) bool {
panic("my hovercraft is full of eels")
})
m.On("F", matcher)
m.F()
}
```
After this change the output will now look like:
```
--- FAIL: TestMatcherPanic (0.00s) …
```
> Mock can be deadlocked by a panic

- mock/mock.go
@Cleancut and I found these changes that should be reverted as they are causing panics after library updates.
This reverts a change that was made in https://github.com/stretchr/testify/pull/1182
That PR makes m.mutex a pointer which now needs to be checked but it's not checked for nil everywhere.
It also reset the mutex in the `.On` function when it could actually have locks from other callers.
- revert `m.mutex` back to a non pointer value
- don't throw away the lock that might be used concurrently in the `.On` function
Fixing panics and crashes in the library after a minor update.
This should also help with these issues:
- https://github.com/stretchr/testify/issues/1208
- https://github.com/stretchr/testify/issues/1210
- https://github.com/stretchr/testify/issues/1206 (introduces a …
> fixing panic in calls to assertion with nil m.mutex

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
Add `WithinTimeRange` and `WithinTimeRangef` assertion methods.
Adds the `WithinTimeRange` assertion function that checks whether the _expected_ time is on or after the _start_ time and on or before the _end_ time. If _end_ is before _start_ the function also fails.
Adds `WithinTimeRange` and `WithTimeRangef` methods on `*Assertions` that calls the `WithinTimeRange` function internally. 
There are cases where one would like to test that a time value is within a certain range, for example when the code being tested updates a timestamp:
```
before := time.Now()
actual := Foo()
after := time.Now()
assert.WithinTimeRange(t, actual.timeStamp, before, after)
```
Currently, the only time-related assertion method is `WithinDuration`, but in the above mentioned situation it leads to one of the …
> Add WithinTimeRange method

- assert/assertions.go
- assert/assertions_test.go
Extended Subset & NotSubset to handle maps
Added some logic to check if each subsets key-value pair are present in the list.
To handle maps in Subset & NotSubset
#1173
> fix: assert.MapSubset (or just support maps in assert.Subset)

- suite/interfaces.go
- suite/suite.go
- suite/suite_test.go
Add opportunity to setup or teardown each subtest
* Added method to the Suite struct that allows to save parent suite (with it's methods) and execute it in future
* Added SetupSubTest interface that allows to execute function before each subtest
* Added TearDownSubTest interface that allows to execute function after each subtest is done
I find very useful to have opportunity to setup/tear down subtest, and I decide to try add it.
```golang
type MySuite struct {
suite.Suite
db *sql.DB
} 
func (ms *MySuite) SetupSuite() {
// abstract code
// setup database in test container and save it into the ms.db
}
func (ms *MySuite) TearDownSubTest() {
// abstract code
// after each subtest run I need to cleanup db
// to avoid conflicts in my tests and make tests more isolated from each other
}
``` …
> Add opportunity to trigger setup/teardown for subtest

- assert/assertions.go
- assert/assertions_test.go
fix bug for checking unsafe.Pointer object isNil.
> fix: fix bug for check unsafe.Pointer isNil

- mock/mock.go
- mock/mock_test.go
`Unset()` doesn't work as expected in documentation. Instead of unsetting call specification it causes panic.
Reason: During call specification filtering `Unset()` changes len of a `ExpectedCalls` slice while using index from original slice. Under some circumstances it tries to reslice elements beyond of the slice boundaries. That causes panic.
The proposed solution uses independent write index to count elements kept in result slice.
Tests (the simplest and  a more complicated cases) and comments are included.
Because core functionality required by users to write tests doesn't work as expected.
```golang
// Unset removes a mock handler from being called.
test.On("func", mock.Anything).Return(nil)  // OK
test.On("func", mock.Anything).Unset()      // panic
```
Closes #1236
> Fix Call.Unset() panic (issue #1236)

- assert/assertions.go
`Error Trace` produce strange output with invalid file paths: it join current execution directory and base source filename, but source file can be located in another directory.
It is especially strange that these path conversions are not needed, since the desired path initially got from stacktrace.
Fix https://github.com/stretchr/testify/issues/1230
Fix https://github.com/stretchr/testify/issues/1268
> Fix `CallerInfo()` source file paths

- assert/assertions.go
- assert/assertions_test.go
This ensures that `assert.Subset` and `assert.NotSubset` consistently fails for tests against maps a key in the subset map is not contained in the map under test.
This ensures that the value obtained by [`reflect/Value.MapIndex`](https://pkg.go.dev/reflect#Value.MapIndex) from the map under test is checked for validity with [`reflect/Value.IsValid`](https://pkg.go.dev/reflect#Value.IsValid).
> MapIndex returns the value associated with key in the map v. [... ] It returns the zero Value if key is not found in the map
This now aligns more closely with `InDeltaMapValues`.
The use of `recover()` was hiding this error by setting the result of the test to be "false" despite the test suite passing. This led to flapping tests where they would succeed if the panic occurred on a missing key before …
> assert: Fix Subset/NotSubset when map is missing keys from the subset

- assert/assertions.go
- assert/assertions_test.go
The `assert.NotContains` error messages now uses `GoString()` for formatting instead of `Stringer()`.
1. Renamed `TestContainsFailMessage` to `TestContainsNotContainsFailMessage` and refactored the test case to use a "test cases" structure.
2. Changed `\"%s\"` to `%#v` in `assert.NotContains`.
3. Added test cases covering both the "len()" / iterable failure messages as well as the Contains/NotContains failure message.
The existing `NotContains` error messages are hard to read.
WAS:
"map[one:%!s(int=1)]" should not contain "one"
IS:
map[string]int{"one":1} should not contain "one"
> assert: fix error message formatting for NotContains

- mock/mock.go
- mock/mock_test.go
This PR fixes #997 
In most go libraries nowadays (etcd, kubernets, aws, etc.) the [functional options pattern](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) is being used:
```go
c := client.New(client.WithTimeout(), client.WithLabel("bar"))
```
```go
type opt struct {
timeout bool
label string
}
type ClientOption func(*opt)
func WithTimeout() ClientOption {
return func(o *opt) {
o.timeout = true
}
}
func WithLabel(v string) ClientOption {
return func(o *opt) {
o.label = v
}
}
func (c *client) New(opts ...ClientOption) *someClient {
options := &opt{}
for _, f := range opts {
f(options)
}
return &someClient{options.timeout, options.label}
}
```
Adds a new argument type `FunctionalOptions`
This wasn't possible before.
Closes #997 #1006
> allow testing for functional options

- .github/workflows/main.yml
- README.md
- assert/assertion_compare.go
- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertion_order.go
- assert/assertions.go
- assert/assertions_test.go
- assert/doc.go
- assert/http_assertions.go
- go.mod
- mock/doc.go
- mock/mock.go
- mock/mock_test.go
- require/doc.go
- require/require.go
- require/require_forward.go
- suite/doc.go
The current implementation of `ObjectsExportedFieldsAreEqual` does not handle (nested) pointer or slices fields. This means it doesn't work for comparing e.g. any Protobuf struct if there is any of these on the Protobuf message.
Here, I am hoisting the reflect.Kind() checking from inside the loop to earlier in the logic. This allows me to take better advantage of the recursiveness of the function for checking equality for different types of structs. All while still maintaining the original functionality, as seen by the fact that the original tests are not altered.
I added a lot of tests cove different cases. It may seems like a lot of tests for this feature, but I used them when developing and since the reflection logic is pretty brittle in general, they were quite necessary for me to be …
> EqualExportedValues: Handle nested pointer, slice and map fields

- .github/workflows/release.yml
This GitHub workflow addition will create new GitHub [release](https://github.com/stretchr/testify/releases) for library when new [tag](https://github.com/stretchr/testify/tags), with matching pattern is pushed.
It does not change current "release process" - developer needs to create tag and push it.
Closes #1295
> Create GitHub release when new release tag is pushed

- go.mod
The `go` directive in go.mod is meant to indicate the minimum supported version.
See: https://go.dev/doc/modules/gomod-ref#go
This allows downstream projects to know what minimum Go version they need for all supported dependencies.
> Fix Go modules version

- README.md
Document explicitly in section about require package that
> These functions must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test. Otherwise race conditions may occur.
It's documented in the official [t.FailNow](http://golang.org/pkg/testing/#T.FailNow), but when someone uses testify and encounters this problem e.g. (my real-world example)
```log
==================
WARNING: DATA RACE
Read at 0x00c0001033c3 by goroutine 44:
testing.(*common).logDepth()
/opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:998 +0x35c
testing.(*common).log()
/opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:985 +0x80
testing.(*common).Errorf()
/opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:1049 +0x58 …
```
> Document that require is not safe to call in created goroutines

- MAINTAINERS.md
As I am supposed to be a maintainer but have almost zero access to actually manage the project, I've found it difficult to help out. Since then my time has become fragmented and as such I'm removing myself as maintainer.
> Remove myself from MAINTAINERS.md

- README.md
Update URLs in README to HTTPS and latest/updated URLs
All `http://` URLs in the README have been updated
`http://` is insecure and older URLs required redirections to reach their final destinations.
> docs: Update URLs in README

- README.md
Update the link for the mockery tool to point to the GitHub Pages site.
GitHub Pages is the better documentation.
> Update mockery link to Github Pages in README

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- mock/mock_test.go
- require/require.go
- require/require_forward.go
Correct spelling mistakes in comments and tests.
- Fix typos only in comments and assert messages.
To improve documentation.
> docs: Fix typos in tests and comments

- assert/http_assertions.go
Fix adding ? when no values passed
Small fix of incorrect URL generation
When no values pased to the HTTPBody method, a ? is incorrectly added, when not essentially required
> Fix adding ? when no values passed

- README.md
- _codegen/main.go
- assert/assertion_format.go
- assert/assertion_forward.go
- require/require.go
- require/require_forward.go
Modify _codegen to use the standard header in generated Go sources.
See https://go.dev/s/generatedcode.
This enables editor support for blocking manual changes in generated sources.
> codegen: use standard header for generated files

- mock/mock.go
Reason log output only if failed in `mock.AssertExpectations`
Details in https://github.com/stretchr/testify/issues/1358
Closes https://github.com/stretchr/testify/issues/1358
Closes https://github.com/stretchr/testify/issues/782
Closes https://github.com/stretchr/testify/issues/414
> mock: AssertExpectations log reason only on failure

- assert/assertions_test.go
Fix flaky `TestNeverTrue` in `assert` package: use a channel to make a synchronized counter to avoid a race condition.
Refactor TestNeverTrue to synchronize the counter.
Fix flaky test which make CI unreliable.
```console
$ go test -race -failfast -count=100 ./...
```
* #1412 A fix for another flaky test
> assert: fix flaky TestNeverTrue

- README.md
"Setup" means an existing arrangement while "set up" is an action.
I wanted to bring to your attention some minor typos in the readme.md file. By fixing these, we can ensure that the intention of the sample code is communicated clearly.
Readme.md has been updated with some spaces.
I'm eager to begin contributing to the testify project, and while acquainting myself with the readme, I noticed a minor typo I'd like to correct. Moving forward, I hope to implement more substantial changes, thus aiding the enhancement of this testing library package that I greatly admire.
> README: fix typos "set up" vs "setup"

- mock/mock.go
Deprecate [`mock.AnythingOfTypeArgument`](https://pkg.go.dev/github.com/stretchr/testify/mock#AnythingOfTypeArgument) which should never have been publicly exposed.
`AnythingOfTypeArgument` is now a type alias to the private `anythingOfTypeArgument` and is marked as Deprecated in godoc. The [`AnythingOfType`](https://pkg.go.dev/github.com/stretchr/testify/mock#AnythingOfType) constructor is still available.
The aim is to completely remove that alias.
* Rename `AnythingOfTypeArgument` to `anythingOfTypeArgument`.
* Add back `AnythingOfTypeArgument` as a type alias of `anythingOfTypeArgument`.
* Mark `AnythingOfTypeArgument` as Deprecated in godoc.
* Documentation is improved to hide implementation details.
API cleanup.
Closes #1434
> mock: deprecate AnythingOfTypeArgument (#1434)

- assert/assertions.go
- assert/assertions_test.go
`reflect.DeepEqual` fails for `time.Time` instances where `time.Equal` would succeed. This is because `reflect.DeepEqual` is checking against some unexported fields, specifically `wall` and `ext`, that change when you add a time zone.  `time.Equal` accounts for this with some bitwise operations as far as I can tell.  
Adds a type switch statement to `ObjectsAreEqual` so special cases can be checked. Default is to use `reflect.DeepEqual`
make `assert.Equal`  match `time.Equal` response.
Closes #1461
> assert: ObjectsAreEqual: use time.Equal for time.Time types

- assert/assertions.go
- assert/assertions_test.go
In `assert.EventuallyWithT`, `assert.CollectT` is used in a concurrent context which may lead to races as explained in https://github.com/stretchr/testify/issues/1391.
We create a `CollectT` per every condition tick and send its errors over a channel. On the reader side of the channel, we cache the `lastTickErrs` so they can be copied over to t once the timeout is fired. The only access to `lastTickErrs` happens in the reader case and the timeout case which both run in the same goroutine.
We cannot use `EventuallyWithT` family of functions/methods in our codebase due to data races it causes.
Closes https://github.com/stretchr/testify/issues/1391.
> fix: make EventuallyWithT concurrency safe

- assert/http_assertions.go
- assert/http_assertions_test.go
http.Request.Body  should be `http.NoBoy` not `nil` when no body.
https://github.com/stretchr/testify/blob/11a6452626f0eacefe8a99889ca4b36f9340488c/assert/http_assertions.go#L15
Test:
```go
func httpReadBody(w http.ResponseWriter, r *http.Request) {
_, _ = io.ReadAll(r.Body)  // will panic
}
assert.HTTPStatusCode(t, httpReadBody, "GET", "/", nil, 200)
```
> assert: fix httpCode and HTTPBody occur panic when http.Handler read Body

- .github/workflows/main.yml
Also update the runners to their latest versions.
> .github: use latest Go versions

- suite/suite.go
- suite/suite_test.go
The order of execution of SetupSubTest and TearDownSubTest methods was changed so that the testing context inside these methods is correct.
* The SetupSubTest was moved to after the SetT that set the child testing context
* The TearDownSubTest was moved to before the deferred SetT that reset the testing context (execution wise)
* The TearDownSubTest and SetT were deferred in one block. This was fine beforehand because a panic in the TearDownSubTest would have had no influence on the "suite.SetT(oldT)". Now since a panic in the TearDownSubTest would lead to omitting the "suite.SetT(oldT)" this defer was split into two separate defers.
There were two problems with the order of execution in the Suite.Run() method:
* One could not access the correct testing context ("s.T()") inside the …
> suite: fix SetupSubTest and TearDownSubTest execution order

- doc.go
- http/doc.go
- http/test_response_writer.go
- http/test_round_tripper.go
Fix deprecation comments for `http`, so the package will be automatically marked as  "Deprecated" on https://pkg.go.dev/github.com/stretchr/testify/http.
- Update comments in the `http` package.
[The official documentation](https://pkg.go.dev) has a special deprecation syntax. It adds yellow background and "Deprecated" tag to the deprecated functions, so the deprecated types and functions are more clearly visible to readers.
Without changes:
With changes in the PR:
- Run [pkgsite](https://pkg.go.dev/golang.org/x/pkgsite/cmd/pkgsite) in `testify` repo.
- Open in browser http://localhost:8080/github.com/stretchr/testify@v0.0.0/http.
> docs: Fix deprecation comments for http package

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- require/require.go
- require/require_forward.go
Updates the doc comments in `Subset` and `NotSubset` functions to include information about the map support added in https://github.com/stretchr/testify/pull/1178.
Simple doc-comment changes only.
At the moment, it's not clear that the `Subset` family of functions supports maps as parameters, while the `Contains` family of functions above do and document it - this behavior makes it seem like `Subset` doesn't support maps.
- https://github.com/stretchr/testify/issues/1173
- https://github.com/stretchr/testify/pull/1178
> Add map support doc comments to Subset and NotSubset

- suite/suite_test.go
We are doing dirty things with [`testing.InternalTest`](https://pkg.go.dev/testing#InternalTest). It looks like test names should have the same prefix as the parent test, like if they were true subtests (testing.T.Run). So until we drop our usage of testing.InternamTest, let's rename the tests.
* Rename the tests when calling testing.RunTests to use the name of the parent test as prefix.
* Also added a few checks of the testing.RunTests result.
CI failure (#1501).
* #1501
> suite: fix subtest names (fix #1501)

- assert/assertions_test.go
- assert/internal/unsafetests/doc.go
- assert/internal/unsafetests/unsafetests_test.go
1. Add infrastructure to split tests that use `unsafe` from other tests.
2. Improve testing of package `assert` with `unsafe.Pointer` values.
1. Isolate tests that use the "unsafe" package in a separate package `./assert/internal/unsafetests`. That way the assert package is not tainted with unsafe.
3. Remove one reference to the private `assert.isNil()` in assert tests.
4. Add more tests of `assert.Nil` and `assert.NotNil` with `unsafe.Pointer`.
`assert/assertions_test.go` is tainted with `unsafe` just because of a single test added in #1319.
> assert: improve unsafe.Pointer tests

- assert/assertions.go
Simpler and faster (also less allocations) in internal function `isNil`.
* Simplify `isNil`: use a switch on `reflect.Value.Kind()` instead of browsing a slice of allowed `Kind`s.
Less code, less complexity, less memory usage, more speed.
> assert: simplify isNil implementation

- assert/assertions.go
Fix multiple issues in `assert.InEpsilonSlice`.
* Fix #1231
* Report the index of the error in the slice
* Stricter checks of arguments
* enforce that slices are of the same type
* check slices length before checking content
* Refactor for less allocations (reuse of reflect.Value)
Cc: @lazywei
Multiple issues in `assert.InEpsilonSlice`.
Closes #1231
#1454 must be adapted @VladPetriv
> assert.InEpsilonSlice: fix expected/actual order and other improvements

- mock/mock_test.go
Refactor tests to use 'append' to build copies of slices instead of manual loops.
Thanks golangci-lint for reporting the style issue.
> mock: refactor TestIsArgsEqual

- mock/mock.go
Two commits to refactor mock.Arguments.Diff to simplify matching by reducing use of `reflect`.
* commit 1: replace multiple comparisons `reflect.TypeOf(actual) == reflect.TypeOf(constant)` with a type switch
* commit 2: refactor `mock.IsType` to take the type early
Reduce use of reflect for more speed and more compiler checks.
> mock: optimize argument matching checks

- .github/workflows/main.yml
Add Go 1.21 in CI.
Note: #1408 must be merged first because `stable` and `oldstable` are supported starting with `setup-go@v4`.
Go 1.21 is released.
See also #1420 and #1408
> CI: add go 1.21 in GitHub Actions

- suite/suite.go
#1501 shows that the panic in the test is reported in [`suite.go:87`](https://github.com/stretchr/testify/blob/331c520966e81450aef3b50956ea4a5db5e0ccdf/suite/suite.go#L87) which is the location of the `failOnPanic` function. This is due to missing calls to [`testing.T.Helper`](https://pkg.go.dev/testing#T.Helper) to help `testing` to skip our framework code.
* Add calls to `t.Helper()` to fix the location where the panic is reported as a test failure.
Bug.
* #696
Cc: @YaroslavDev
> suite: fix recoverAndFailOnPanic to report test failure at the right location

- assert/assertions.go
- assert/assertions_test.go
Previously, the use of %s with array objects meant you would get an error like this:
"[%!s(int=1) %!s(int=2) %!s(int=3)]\" should have 4 item(s), but has 3
Use %v instead, which provides a much nicer error.
"[1 2 3]" should have 4 item(s), but has 3
Fixes #1482.
> assert: better formatting for Len() error

- mock/mock.go
- mock/mock_test.go
Prevent `(*Mock).AssertExpectations` from failing if test expectations are not met but the test has already been marked as "Skipped".
* Add check to `(*Mock).AssertExpectations` such that if the `*testing.T` is already marked skipped, we just return true immediately.
* Add a unit test (`Test_Mock_AssertExpectations_Skipped_Test`) for the new behavior.
Normally the decision to skip a test is made early in the test function, but on occasion it might be the case that you have already set up some mock expectations _before_ you call `t.Skip`.  If that's the case, then a call to `AssertExpectations` will fail, which is not intended.
```go
func TestExample(t *testing.T) {
val := new(MockedValue)
val.On("DoThing", 1, 2).Return(3, 4)
defer val.AssertExpectations(t)
if os.GetEnv("foo") == "" {
// …
```
> Ensure AssertExpectations does not fail in skipped tests

- suite/suite.go
- suite/suite_test.go
As pointed out in issue #1520, if the suite is not initialised properly (by calling the `Run` function), then calling `suite.Require()` or `suite.Assert()` will result in a deadlock.
This commit fixes that by panicking if the suite is not initialised properly. This is justified because the suite is intended to be triggered in the right way. If the user does not do that, this panic will nudge them in the right direction.
It has to be a panic because, at this point, we don't have access to any `testing.T` context to gracefully call a `t.Fail()`. Also, these two functions are not expected to return an error.
Fixes #1520
> suite: fix deadlock in suite.Require()/Assert()

- .github/workflows/main.yml
Update the github workflows `setup-go` to V5
Update the github workflows `setup-go` to V5
Deprecation warning https://github.com/stretchr/testify/actions/runs/7971877138
Why V5? The upgrade including node16 to node20 is in V5
https://github.com/actions/setup-go/releases/tag/v5.0.0
No warning https://github.com/stretchr/testify/actions/runs/7991605261
Closes #1541
> Update Github workflows setup-go to V5

- assert/assertions.go
- assert/assertions_test.go
This PR allows to use `EqualExportedValues` with pointers to structs.
> Support Pointer to Struct in EqualExportedValues

- assert/assertions.go
- assert/assertions_test.go
- assert/http_assertions.go
- assert/http_assertions_test.go
The http assertions do not use the `msgAndArgs` at all. This commit fixes that.
Not directly related, but stemmed from looking into #316 
Closes #1324
> http_assertions: honour the msgAndArgs provided with each assertion

- .github/ISSUE_TEMPLATE/bug_report.md
- assert/assertions_test.go
- suite/suite_test.go
fix typos in documentation, comments and tests
I looked at the documentation, then found one typo in Panic: "functon" instead of "function"
So decided to check a bit further.
I used the following tools to validate the typos:
* https://github.com/crate-ci/typos
* https://github.com/streetsidesoftware/cspell-cli
* https://github.com/codespell-project/codespell
I applied automatic fixes, then reviewed them manually one by one, before committing and opening this PR
None
> fix typos in comments and tests

- .github/workflows/release.yml
Enable the auto generated release notes on the auto-generated releases.
* Enable `generate_release_notes` on the release workflow.
To be able to see what is in a release and who contributed.
> Include the auto-release notes in releases

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
Add `assert.NotImplements` (and variants)
Added `assert.NotImplements` (and variants)
There was no way to test an object did not implement a specific interface yet. Its counterpart does exist, so it was somewhat surprising to not be able to test the inverse.
```golang
import (
"crypto/ecdsa"
"crypto/elliptic"
"crypto/rand"
"github.com/stretchr/testify/assert"
"github.com/stretchr/testify/require"
)
func Test_NotASigner(t *testing.T) {
e, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
require.NoError(t, err)
assert.NotImplements(t, (*crypto.Signer)(nil), e.Public()) // public key only isn't a signer
}
```
Closes #1065
> Add `NotImplements` and variants

- assert/assertions.go
- assert/assertions_test.go
Add a `PanicAssertionFunc` to ease writing table-driven tests for panic assertion.
- Add `PanicAssertionFunc` for table driven.
- My team uses panic assertion a lot :smile: 
- Useful for building panic assertion
- There is an issue reported for this one as well: #730
```go
func ExamplePanicAssertionFunc() {
t := &testing.T{} // provided by test
tests := []struct {
name      string
panicFn   func()
assertion PanicAssertionFunc
}{
{"with panic", func() { panic(nil) }, Panics},
{"without panic", func() {}, NotPanics},
}
for _, tt := range tests {
t.Run(tt.name, func(t *testing.T) {
tt.assertion(t, tt.panicFn)
})
}
}
```
https://github.com/fahimbagar/testify/blob/cb954e70769531b0462ae2f713c12c74e64ad69c/assert/assertions_test.go#L2410-L2427
Closes #730
> Add PanicAssertionFunc

- assert/assertions.go
- require/requirements.go
The tHelper interface is defined only for internal usage. We don't need a "hard" type for it as we don't define methods on it. Let's make is just a alias to the anonymous interface it represents.
Note: we are already using type aliases elswhere, and type aliases were introduced a long time ago in Go 1.9.
* assert: `tHelper` becomes a type alias
* require: `tHelper` becomes a type alias
The `tHelper` symbol is not needed at runtime. This should reduce resource usage (yes, negligible).
* #1422 is also related to the `interface { Helper() }` type, but not dependent
> assert: make tHelper a type alias

- .gitignore
Ignore binaries produced by `go test -c`.
* Add `assert/assert.test`, `require/require.test`... to `.gitignore`.
Ease maintenance as there is no risk of committing those files by mistake.
N/A
> .gitignore: ignore "go test -c" binaries

- mock/mock.go
We already have access to the argument value so there's no need to retrieve it again for the error message.
> Do not get argument again unnecessarily in Arguments.Error()

- mock/mock.go
Improve API doc of package [`mock`](https://pkg.go.dev/github.com/stretchr/testify/mock):
- add godoc links
- indent example code
Readability.
> mock: improve doc

- assert/assertion_compare.go
- assert/assertion_compare_test.go
- assert/assertion_order.go
Mark [`assert.CompareType`](https://pkg.go.dev/github.com/stretchr/testify/assert#CompareType) as _deprecated_.
Commits step by step:
* Refactor tests to free the `compareResult` symbol name: d75ed1dbce63d7f994be0afb3eabe1886c722844, 539cfd9c2763e2dab63926ed9fc435e478346f2b
* Rename `CompareType` to `compareResult`: fc30ce69c521b8b47adaf4f812bde58bc677767a
* Reinstate `CompareType` but mark it as _deprecated_: 05f46a65dc8c220d160a5dac12d81fe97b51c0be
[`assert.CompareType`](https://pkg.go.dev/github.com/stretchr/testify/assert#CompareType) has been introduced by 0b4ff03cda5c8eb0150a14ffbaaa088fd777d6ba and published since v1.6.0, but it is in fact only for internal usage and should never have been exposed.
A search of usage of `assert.CompareType` on GitHub shows no results: …
> assert: deprecate CompareType

- mock/mock.go
the comment about this function is not updated with the final implementation
just the comment above the func
its misleading
some relevant links to the PR that added `FunctionalOptions`
https://github.com/stretchr/testify/pull/1023
[suggestion 1](https://github.com/stretchr/testify/pull/1023/files/3b93fae0ea161f8d0ca47dd7aa3d8a949799d261#r1065311500)
[suggestion 2](https://github.com/stretchr/testify/pull/1023/files/3b93fae0ea161f8d0ca47dd7aa3d8a949799d261#r1065309374)
> mock: fix FunctionalOptions docs

- README.md
- doc.go
Add a call to action to the README to use [testifylint](https://github.com/Antonboom/testifylint).
Testify has many pitfalls due to the quality of some parts of the API, a lot of these cannot be fixed in testify without breaking the Go modules compatibility promise. [testifylint](https://github.com/Antonboom/testifylint) can warn users when they fall in these pits.
> README: link out to the excellent testifylint

- assert/assertion_compare.go
- assert/assertion_compare_test.go
fix #1581
I was eager to use [Time.Compare](https://pkg.go.dev/time#Time.Compare), but it was added only in go 1.20
> Fix time.Time compare

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- require/require.go
- require/require_forward.go
The example used for `EventuallyWithT` documentation doesn't actually pass.
Updated the example to be correct by swapping the times used for `waitFor` and `tick`
I was looking at the docs and, based on the example, mistakenly set `waitFor` to be a shorter time than `tick`, which means `condition` never gets called. Hopefully this helps other people avoid the same mistake.
> Correct the EventuallyWithT and EventuallyWithTf example

- mock/mock.go
Follow-up to #1441: more doc for deprecated [`mock.AnythingOfTypeArgument`](https://pkg.go.dev/github.com/stretchr/testify/mock#AnythingOfTypeArgument).
Improve go doc.
I had a look to usages of [`mock.AnythingOfTypeArgument`](https://pkg.go.dev/github.com/stretchr/testify/mock#AnythingOfTypeArgument) in the wild on GitHub:
https://github.com/search?q=mock.AnythingOfTypeArgument+language%3Ago+NOT+repo%3Astretchr%2Ftestify&type=code
This change should give more guidance for fixing the issue in downstream projects.
* #1441, #1434
* mattermost/mattermost-plugin-confluence#108, mattermost/mattermost-plugin-cloud#154, mattermost/mattermost-plugin-jira#1030
> mock: document more alternatives to deprecated AnythingOfTypeArgument

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- require/require.go
- require/require_forward.go
The EqualValues docstring is ambiguous to how it actually behaves, this docstring more concisely describes the current behavior.
Update docstring for all EqualValues functions
The ambiguity caused issues, such as #1576 where an update changed the arguably broken behaviour without breaking the ambiguous contract.
#1576 this does not necessarily resolve the issue, nor does it preclude reverting the behavior. The aim here is only to make the documentation match the current behaviour.
> Correctly document EqualValues behavior

- assert/assertions.go
- assert/assertions_test.go
The regexp package works more efficiently on bytes; if you have bytes, it is easier to pass these directly to assert.Regexp than to convert them to a string first.
In addition, FindIndex/FindStringIndex are unnecessary here because we immediately throw away the result - let's just call Match() instead.
More efficient test calls, fewer casts in test code. 
Updates #1585.
> assert.Regexp: handle []byte array properly

- assert/assertions.go
- assert/yaml/yaml_custom.go
- assert/yaml/yaml_default.go
- assert/yaml/yaml_fail.go
Make the YAML module dependency required for [`assert.YAMLEq`](https://pkg.go.dev/github.com/stretchr/testify/assert.YAMLEq) (and family) pluggable.
* Add package `github.com/stretchr/testify/assert/yaml` that wraps the dependency. It exposes just `func Unmarshal([]byte, interface{}) error` (the only function imported from `gopkg.in/yaml.v3` for `assert`).
* Add 3 implementations of that package which are activated by build tags. The default implementation is the existing behavior and just wraps [`gopkg.in/yaml.v3.Unmarshal`](https://pkg.go.dev/gopkg.in/yaml.v3#Unmarshal).
The dependency on `gopkg.in/yaml.v3` for YAML deserialization (used by `assert.YAMLEq`) is causing painful maintenance work. Both for this project, and for downstream projects (end users). Unfortunately we can't just …
> assert: make YAML dependency pluggable via build tags

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
Add new assertion `NotElementsMatch` which asserts whether 2 lists are NOT equal ignoring the order of the elements. If there are duplicate elements, the number of appearances of each of them in both lists should not match. This is an inverse of `ElementsMatch`.
- Add new assertion `NotElementsMatch` 
- No assertion for comparing 2 lists do NOT contain the exact same elements, irrespective of order. (inverse of `ElementsMatch`)
https://github.com/stretchr/testify/issues/1594
https://github.com/stretchr/testify/discussions/1592
> assert: new assertion NotElementsMatch

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- require/require.go
- require/require_forward.go
Grammar fixes in doc: _asserts that at none_ -> _asserts that none_
```console
$ grep 'that at none' */*.go
assert/assertion_format.go:// NotErrorIsf asserts that at none of the errors in err's chain matches target.
assert/assertion_forward.go:// NotErrorIs asserts that at none of the errors in err's chain matches target.
assert/assertion_forward.go:// NotErrorIsf asserts that at none of the errors in err's chain matches target.
assert/assertions.go:// NotErrorIs asserts that at none of the errors in err's chain matches target.
require/require.go:// NotErrorIs asserts that at none of the errors in err's chain matches target.
require/require.go:// NotErrorIsf asserts that at none of the errors in err's chain matches target.
require/require_forward.go:// NotErrorIs asserts that at none of …
```
> fix: grammar in godoc

- assert/assertions.go
- assert/assertions_test.go
- require/requirements_test.go
`collect.FailNow()` should exit goroutine without a panic to be usable with `require` package.
`collect.FailNow()` just does `runtime.Goexit()` instead of `panic()`. For example `FailNow()` from `testing` package [behaves similarly](https://cs.opensource.google/go/go/+/refs/tags/go1.21.2:src/testing/testing.go;l=973).
I just want `require` package to be usable with `EventuallyWithT` e.g. I want this example to pass but it panics:
```go
package main
import (
"testing"
"time"
"github.com/stretchr/testify/assert"
"github.com/stretchr/testify/require"
)
func TestRequireEventuallyWithT(t *testing.T) {
state := 0
require.EventuallyWithT(t, func(c *assert.CollectT) {
defer func() { state += 1 }()
require.True(c, state == 2)
}, 100*time.Millisecond, 10*time.Millisecond)
}
```
See …
> assert: collect.FailNow() should not panic

- mock/mock.go
Remove unnecessary use of [reflect](https://pkg.go.dev/reflect) in the implementation of [mock.FunctionalOptions()](https://pkg.go.dev/github.com/stretchr/testify/mock#FunctionalOptions).
* Change the internal representation of `FunctionalOptionsArgument` to be a slice of arguments to match the variadic argument of `FunctionalOptions`.
* Remove unnecessary use of `reflect`.
* Simpler code
* Runtime speed
> mock: simplify implementation of FunctionalOptions

- mock/mock.go
- mock/mock_test.go
When using mocks in large integration tests, it is very difficult to find places of unexpected function calls.
I suggest adding information about the location of the call.
> mock: caller information for unexpected method call

- mock/mock.go
- mock/mock_test.go
Add helper method to declare the order of the mock calls.
* add `InOrder(calls ...*Call)` helper method to declare the order of mock calls by calling `NotBefore()`
This is probably the only feature I miss from `gomock.InOrder()`, it is more intuitive and cleaner to declare the order of the mock calls. Probably most cases can be satisfied with this method.
```
InOrder(
mockedService1.On("TheExampleMethod", 1, 2, 3).Return(4, nil),
mockedService2.On("TheExampleMethod2", true).Return(),
mockedService3.On("TheExampleMethod3", "abc", 3).Return(false, nil),
)
```
Closes #1639
> mock: in order mock calls

- .github/workflows/main.yml
Run tests for Go 1.22.
Add Go 1.22 to test matrix.
Make sure the current and future code stays functional on latest released Go version.
N/a
> .github/workflows: Run tests for Go 1.22

- README.md
- suite/doc.go
Document that at this time suite cannot support Parallel tests
Document this in README.md and suite's godoc.
Suite will always be broken when using parallel tests in testify v1. The only clean fix is a breaking change described in #1109 
Related to
* #934 
* #187
> Document suite's lack of support for t.Parallel

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
The library had implementations for ErrorIs, ErrorAs and NotErrorIs but
was missing a NotErrorAs implementation. This PR adds a NotErrorAs
function, which is the inverse of the ErrorAs function.
* Adds `NotErrorAs` function and test
* Improves existing tests (`TestErrorIs`, `TestNotErrorIs` and `TestErrorAs`) by comparing assertion result and `testing.T` flag.
* Clarifies documentation for existing `NotErrorIs` function
There's already an inverse of `ErrorIs`, `ErrorAs` should have an inverse as well.
Closes #1066
> Add assertion for NotErrorAs

- assert/assertions_test.go
- assert/yaml/yaml_custom.go
- assert/yaml/yaml_default.go
Correct spelling mistakes in comments.
- Fix typos only in Go comments in the `assert` directory.
To improve documentation.
> assert: fix typos in comments

- suite/suite_test.go
Fix TestFailfastSuite when run with go test flag -count=X where X greater than 1.
So we don't get false test failures causing confusion.
> suite: fix test failures

- mock/mock.go
I had a situation where I did not have full visibility into what was returned by one of my mocked functions.  In this light, it is helpful to have the recorded arguments in the `mock.Calls` field.  I was surprised to find that for the recorded `Call`s `ReturnArguments` is left empty and is only used for `ExpectedCalls`.  This PR now properly records the ReturnArguments for a `Call`.
> Record Return Arguments of a Call

- _codegen/main.go
- require/require.go
- require/require.go.tmpl
The comments for the require package were just copied over from the assert package when generating the functions. This could lead to confusion because
1. The code-examples were showing examples using the assert package instead of the require package
2. The function-documentation was not mentioning that the functions were calling `t.FailNow()` which is some critical information when using this package.
1. Added a "replace" function to the template
2. require.go.tmpl now replaces the package name accordingly
3. require.go.tmpl now adds another line to the function-docs explaining the difference to the assert-function
When new developers are coming in they most likely did not go through the github-documentation for every package used in the application. But what they do is read the …
> Generate better comments for require package

- assert/assertions.go
- assert/assertions_test.go
Remove type validation in EqualExportedValues
See #1584.
> assert.EqualExportedValues: accepts everything

- README.md
- doc.go
Remove Testify V2 notice on `README.md` since it won't happen
- Remove Testify V2 notice on `README.md`
According to this announcement https://github.com/stretchr/testify/issues/1089#issuecomment-1812734472 from @dolmen 
> So, as the current only active maintainer, I'm declaring that v2 will never happen. Or at least a v2 of the github.com/stretchr/testify module with such major breaking changes.
Issues that can be closed:
https://github.com/stretchr/testify/issues/1089
> README: replace Testify V2 notice with @dolmen's V2 manifesto

- assert/assertions.go
- assert/assertions_test.go
Comparing Infs should fail as described in related issue
Closes #1662
> Fix issue #1662 (comparing infs should fail)

- assert/assertions.go
- assert/assertions_test.go
Reduces the confusion assosciated with NotSame that previously would check nothing if any of the values is not a pointer. The changes made were tested using TestSame, TestNotSame, and Test_samePointers tests, and the changes did clear the tests.
1. Modified samePointers to return another bool value(ok) that would determine if the 2 values are of pointer type or not, while the returned "same" bool value would determine if the 2 pointers are same.
2. Modified assert.NotSame to call Fail() if the 2 values are either i)pointers pointing to the same address or ii)either/both of the values are not pointers.
3.  Modified assert.Same to call Fail() if the 2 values are either i)pointers not pointing to the same address or ii)either/both of the values are not pointers.
4. Modified Test_samePointers …
> NotSame should fail if args are not pointers #1661

- mock/mock_test.go
Increased timeouts in the `Test_Mock_Called_blocks` test to improve stability and reduce flakiness in CI environments.
* Modified the timeout in the `select` block from `1ms` to `10ms` to allow more time before checking for the channel.
* Adjusted the `After` clause in the mocked service's `asyncCall` from `2ms` to `20ms` to ensure sufficient time for the asynchronous operation to complete.
The changes were necessary to address intermittent test failures caused by tight timing constraints in low-powered CI environments. By increasing the timeouts, we aim to enhance the reliability of our tests, ensuring they pass consistently across different execution environments.
Closes #1666
> Increase timeouts in Test_Mock_Called_blocks to reduce flakiness in CI

- mock/mock.go
- mock/mock_test.go
Closes Functional Options testing broken for indirect calls #1380. The fix is consists of not comparing the the function names, as it is already asserted when comparing `expectedValues` and `actualValues`
* Adds test `Test_Mock_AssertExpectationsFunctionalOptionsTypeIndirectly` which would fail without the fix
* Adds test `Test_Mock_AssertExpectationsFunctionalOptionsType_Diff` to examine behavior of slightly different functional options in expected vs actual.
* Changes the `funcName` implementation to only compare the relevant last part, if applicable. This aids in reading the diff that is produced when the function names don't. match (for go1.20 or higher)
The choice was made to omit the comparison of function names completely, instead of comparing only the relevant last part. The …
> fix: compare functional option names for indirect calls

- _codegen/main.go
- suite/suite_test.go
This PR replaces function usages from `io/ioutil` with the same functions from `io` and `os`. 
- replace `ioutil.ReadFile` with `os.ReadFile`
- replace `ioutil.ReadAll` with `io.ReadAll`
[io/ioutil](https://pkg.go.dev/io/ioutil) is deprecated:
> Deprecated: As of Go 1.16, the same functionality is now provided by package [io](https://pkg.go.dev/io) or package [os](https://pkg.go.dev/os), and those implementations should be preferred in new code. See the specific function documentation for details.
#1305 #1386 #1407 #1469
> Replace deprecated io/ioutil with io and os

- assert/assertions.go
- assert/assertions_test.go
When an assertion fails in assert.ErrorAs, log the target error type rather than its value.
Passes the target error type, rather than the target itself, to the Fail() call in assert.ErrorAs. Also, modifies buildErrorChainString to support go 1.20 error wrapping, and to include the error type in its output when called by assert.ErrorAs.
The existing error message was confusing - see #1343 
Closes #1343
> assert.ErrorAs: log target type

- assert/assertion_compare.go
Error messages for `Positive` and `Negative` asserts are malformed, because of an extra argument (0) passed to the formatting function. This PR fixes that.
I moved error message formatting out of `compareTwoValues` function to its callers. That way all messages are formatted independently and correctly.
The following test:
```
func TestNegative(t *testing.T) {
assert.Negative(t, 1)
}
```
fails with the following output:
```
--- FAIL: TestNegative (0.00s)
assertion_compare.go:360: 
Error Trace:    test_test.go:20
Error:          "1" is not negative%!(EXTRA int=0)
Test:           TestNegative
Messages:       []
```
Error message is suffixed with `%!(EXTRA int=0)`, because `Negative` assert uses same function as other comparison asserts, and it includes error formatting.
Same bug occurs for …
> Fix failure message formatting for Positive and Negative asserts

- mock/mock.go
- require/doc.go
These comments are adapted from `t.FailNow()`'s own documentation.
I added warnings on high-level APIs likely to be used by end users, and leading to `t.FailNow()` being called.
Such additional documentation can spare users headache in situations where ignoring the warnings would lead to test suites hanging forever
Closes #1701
> Document consequences of calling t.FailNow()

- mock/mock.go
Updates the docs to clarify how unset works.
Doc update
Unset docs indicate "a" handler is removed when called when all handlers satisfying the arguments in the call unset is invoked on are removed.  This clarifies the behavior and provides a sample.  Also clarifies that Unset can only be called on static input arguments.
Closed #1621
> chore: update docs for Unset #1621

- .ci.readme.fmt.sh
- .github/workflows/main.yml
- .mdsf.json
- README.md
Format Go code snippets in the README with `gofmt`.
- Replace spaces with tabs.
- Add empty lines between imports.
- Remove empty lines in blocks.
- Add [`mdsf`](https://github.com/hougesen/mdsf) to check formatting in CI.
The code should be formatted the same as `gofmt` even in the documentation.
> README: apply gofmt to examples

- MAINTAINERS.md
I propose granting Christophe Colombier (@ccoVeille) approver on testify.
* Correct the existing list of approvers.
* Add @ccoVeille as approver.
For the more than the last year I have seen consistent valuable contributions from @ccoVeille in issue triage, pull request reviews, and pointing me in the direction of unblocked work I can progress. I think he will make a great approver, and one day maintainer too.
> Propose Christophe Colombier (ccoVeille) as approver

- assert/assertions.go
- assert/assertions_test.go
Addresses #1424.
`Eventually` and `EventuallyWithT` current must always wait at least the polling duration before they can succeed. This PR starts checking the condition immediately. The assertion still fails if the initial check of the condition takes longer than the configured timeout.
This will provide a small optimization to callers, because tests can complete more quickly than they did before if conditions are met already.
> assert: check early in Eventually, EventuallyWithT, and Never

- assert/assertions.go
- assert/assertions_test.go
This improves the UX of users of `ErrorIs()` in case the value `nil` is passed for `err` while an error was expected.
- added check if `err == nil && target != nil` -> return a special error-string 
- updated relevant test case
The error message when an error is expected but `err` is `nil` (a common occurence in the world of testing) could be more helpful, e.g.:
```
(before)
some_test.go:20:
Error Trace:    /[...]/some_test.go:20
Error:          Target error should be in err chain:
expected: "sample error message"
in chain:
```
vs
```
(after)
some_test.go:20:
Error Trace:    /[...]/some_test.go:20
Error:          Expected error with "sample error message" in chain but got nil.
```
> Improve ErrorIs message when error is nil but an error was expected

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
`Subset`/`NotSubset` failed with "<subset> has unsupported type map" when called with a `list` of kind `array`/`slice` and `subset` of kind `map` which should work based on the documentation.
I added support and test cases for these inputs.
Implementation should conform to documentation.
> fix Subset/NotSubset when calling with mixed input types

- assert/assertions.go
- assert/assertions_test.go
The following changes were made to improve the error messages
Improve ErrorAs failure message when error is nil
Before:
```
Should be in error chain:
expected: *assert.customError
in chain:
```
After:
```
An error is expected but got nil.
expected: *assert.customError
```
The message `An error is expected but got nil.` is the one already reported by `assert.Error`
This follows the changes that were made with #1681
- #1681
Closes #1733
- #1733
> Improve ErrorAs failure message when error is nil

- assert/yaml/yaml_custom.go
- assert/yaml/yaml_default.go
- assert/yaml/yaml_fail.go
This PR removes outdated build constraints.
Remove unnecessary `// +build` comments from files in the `assert/yaml` package.
To cleanup the code.
The ["Build constraints"](https://pkg.go.dev/cmd/go#hdr-Build_constraints) says:
> Go versions 1.16 and earlier used a different syntax for build constraints, with a "// +build" prefix. The gofmt command will add an equivalent //go:build constraint when encountering the older syntax.
It's a safe change because the minimum supported version by `testify` is Go 1.17.
> assert: remove deprecated build constraints

- assert/assertions.go
- assert/assertions_test.go
Format assertions files with gofumpt
None, except formatting.
- Having a cleaner code base
- Be able to use gofumpt locally
Replaces #1736 created with the wrong fork.
- #1736
> Format assertions files with gofumpt

- .ci.gofmt.sh
- .ci.gogenerate.sh
- .ci.govet.sh
- .ci.readme.fmt.sh
Fix shebang in .ci.*.sh scripts to ease running on platforms where bash is not in /bin/bash (ex: MacOS).
> CI: fix shebang in .ci.*.sh scripts

- assert/assertion_compare_test.go
- assert/assertion_order_test.go
- assert/assertions_test.go
- assert/forward_assertions_test.go
- assert/http_assertions_test.go
- require/forward_requirements_test.go
- require/requirements_test.go
Enable parallel testing for almost all tests in packages 'assert' and 'require' by calling t.Parallel() as the first line of the test.
A few tests are incompatible and will be fixed separately. They are marked with a FIXME.
Incompatible tests: TestFileExists, TestNoFileExists, TestDirExists, TestNoDirExists.
Before:
```console
$ go test -count=10 ./assert ./require
ok  	github.com/stretchr/testify/assert	7.575s
ok  	github.com/stretchr/testify/require	1.501s
```
After:
```console
$ go test -count=10 ./assert ./require
ok  	github.com/stretchr/testify/assert	1.703s
ok  	github.com/stretchr/testify/require	1.245s
```
* `assert`: add `t.Parallel()` in almost all top level tests.
* `require`: add `t.Parallel()` in all top level tests.
The testsuite runs faster if GOMAXPROCS > 1.
* …
> assert,require: enable parallel testing on (almost) all top tests

- suite/stats_test.go
This test case verifies that the Passed method returns false when all tests in the suite fail
Added a test case to check the scenario where all tests fail.
This test is important to ensure that the Passed method correctly identifies the overall failure state of a test suite when none of the individual tests pass.
This test can be used as a part of the test suite to validate the behavior of the Passed method under failure conditions.
None
> suite.Passed: add one more status test report

- assert/assertions.go
Reuse variable indexes instead of duplicating them.
Avoid using the same variable multiple times with [fmt.Sprintf](https://pkg.go.dev/fmt#hdr-Explicit_argument_indexes)
> Use indexed formats like `%#[1]v` to remove parameter duplication (we should do that also in Same/NotSame code, but in a separate PR).
> _Originally posted by @dolmen in https://github.com/stretchr/testify/pull/1738#discussion_r2086147685_
> assert.Same/NotSame: improve usage of Sprintf

- assert/assertions.go
Shortcut in `assert.JSONEq` once we have validated that 'expected' is valid JSON, and 'actual' is the exact same string.
* add shortcut in `JSONEq`
Faster check for the very common case where the test succeeds because the strings are equal.
#1755 same, but for YAMLEq
> assert.JSONEq: shortcut if same strings

- assert/assertions.go
Shortcut in `assert.YAMLEq` once we have validated that 'expected' is valid JSON, and 'actual' is the exact same string.
* add shortcut in `YAMLEq`
Faster check for the very common case where the test succeeds because the strings are equal.
#1754 same, but for JSONEq
> assert.YAMLEq: shortcut if same strings

- assert/assertions_test.go
Repost of #1737.
check test failure message for Empty and NotEmpty 
Only the tests are updated, code is unchanged.
Previously, the tests were checking only the result of the asserter.                                                                                                                       
Using captureTestingT helper allows to check the error message   
It allows us to make sure the error message reported are OK.
This is a proof of concept PR that follows up #1737 that was closed because:
- it was not using a fork
- there were a lot of changes to review.
- #1737
> assert: check test failure message for Empty and NotEmpty 

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
Document the [`assert.Empty`](https://pkg.go.dev/github.com/stretchr/testify/assert#Empty) rules more comprehensively. This exposes our quirks to the user to avoid wrong expectations.
Add many many many more test cases that document edges cases and will allow to catch breaking changes and avoid regressions.
* improve doc of `assert.Empty`, `assert.NotEmpty` (and their generated childs in package `require`)
* add many test cases for the internal `isEmpty`. They are added in the current style for now, but I have plans for a future refactoring (using table tests).
[`assert.Empty`](https://pkg.go.dev/github.com/stretchr/testify/assert#Empty) has quirks which desserve to be documented for our users, and for contributors.
The extensive test suite will help to ease future refactorings of Testify …
> assert.Empty: comprehensive doc of "Empty"-ness rules

- doc.go
Improve package doc of [`github.com/stretchr/testify`](https://pkg.go.dev/github.com/stretchr/testify)
Add godoc links to other packages `assert`, `require`, `mock`, `suite`.
> doc: improve godoc of top level 'testify' package

- assert/assertions.go
- assert/assertions_test.go
Refactor `isEmpty` which is the backend of `assert.Empty` and `assert.NotEmpty`.
* `add Benchmark_isEmpty` that shows that some cases of `isEmpty` allocate memory
* split `isEmpty` into `isEmpty` and `isEmptyValue` for more efficient recursion when checking pointer values
* simplify `isEmptyValue` by using `reflect.Value.IsZero` (available since Go 1.13, so after the initial implementation of `assert.IsEmpty`).
* simpler implementation
* faster:
* check for zero value using `reflect.Value.IsZero` which doesn't allocate memory.
> assert: faster and simpler isEmpty using reflect.Value.IsZero

- assert/assertions_test.go
This change ensures both success and failure paths are tested for `EqualValues`, covering the error formatting and failure reporting code that was previously untested.
Coverage improvement:
- EqualValues: 57.1% → 100.0%
- Overall package: 68.4% → 68.5%
Note: this change has been made with the help of the [sketch.dev](https://sketch.dev) coding agent.
Extend `TestNotEqualValues` to also test `EqualValues` by leveraging the fact that they are inverse functions. The same test cases are used to verify that `EqualValues` returns the opposite result of `NotEqualValues`.
The test function was renamed to `TestEqualValuesAndNotEqualValues` to reflect its dual purpose while maintaining all existing test logic.
* Increase test coverage
* Test [sketch.dev](https://sketch.dev)
> assert.EqualValues: improve test coverage to 100%

- assert/assertions.go
Move the stackFrameBufferSize const which was in package scope but used only by CallerInfo, into CallerInfo body.
* Move the `stackFrameBufferSize` const into `CallerInfo` body
* Small refactor use of stack frame handling to remove one reference to that const
Cleanup: the `stackFrameBufferSize` constant doesn't pollute the package scope anymore.
That constant wasn't even defined near the `CallerInfo` body, but at the top of the file, which made it harder to lookup.
> assert.CallerInfo: micro cleanup

- suite/stats.go
- suite/suite.go
Refactor handling of stats in [`suite.Run`](https://pkg.go.dev/github.com/stretchr/testify/suite#Run) with the goal of reducing indented blocks to improve readability.
The [`SuiteInformation`](https://pkg.go.dev/github.com/stretchr/testify/suite#SuiteInformation) methods now handle being called with a nil receiver to work as no-op. This allows to call them from [`suite.Run`](https://pkg.go.dev/github.com/stretchr/testify/suite#Run) without nil checks blocks, so with improved readability thanks to the removal of indented blocks.
Improve readability of [`suite.Run`](https://pkg.go.dev/github.com/stretchr/testify/suite#Run).
N/A
> suite.Run: refactor handling of stats for improved readability

- mock/mock.go
Improve the error message raised my AssertNumberOfCalls.
This specify exactly what method mock is failing the test.
When running my tests, I did not see any clear information of the exact method that was not correctly mocked. So I wanted to fix it.
Example of the new error message:
```
=== RUN   Test_Mock_AssertNumberOfCalls
/tmp/testify/mock/mock_test.go:1644:
Error Trace:    /tmp/testify/mock/mock_test.go:1644
Error:          Not equal:
expected: 2
actual  : 3
Test:           Test_Mock_AssertNumberOfCalls
Messages:       Expected number of calls (2) of method (Test_Mock_AssertNumberOfCalls) does not match the actual number of calls (3).
/tmp/testify/mock/mock_test.go:1644:
Error Trace:    /tmp/testify/mock/mock_test.go:1644
Error:          Should be true
Test: …
```
> mock.AssertNumberOfCalls: improve error msg

- mock/mock.go
- mock/mock_test.go
Back-port only the fix to #1785 into the release/1.11 branch to prepare for v1.11.1.
* Cherry pick c952903 and resolve conflicts
Previously passing tests were broken by v1.11.0.
Closes #1785
> Backport #1786 to release/1.11: mock: revert to pre-v1.11.0 argument matching behavior for mutating stringers

- suite/suite.go
- suite/suite_test.go
This PR improves method signature validation in Testify's suite execution by ensuring that invalid methods are logged, and valid methods continue to execute.
* Added validation of method signatures (checking for arguments and return values) at an earlier stage, after method filtering.
* Replaced `t.Fatalf` with `t.Errorf` to report invalid method signatures while allowing the test suite to continue executing valid methods.
* Introduced additional test cases to cover both valid and invalid method signatures.
* To ensure that invalid method signatures in the suite are reported without stopping execution, allowing valid methods to run and improving overall test suite behavior.
* Closes #1508
> suite: validate method signatures and continue execution for valid tests

- assert/assertions.go
- assert/assertions_test.go
Truncate object representations in test failure output messages that would cause the message to be too long to scan.
This is a different approach than that in #1559. I feel this is more appropriate because is it safer. The other approach has the potential to allocate excessive memory and to print excessive output to the console.
* Make the message line indenter show an appropriate error if it fails to scan a line from the message.
* Use the existing `truncatingFormat` function to truncate potentially long objects in assertions which format expected/actual values in full.
* Parameterize the format string used by `truncatingFormat`.
* Reduce the limit used by `truncatingFormat` by almost half to support failure messages showing both long expected and long actual values on the same line.
* …
> assert: truncate very long objects in test failure messages

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/doc.go
- mock/mock.go
- require/doc.go
- require/require.go
- require/require_forward.go
- suite/suite.go
Godoc does not have inline code blocks. Look to the standard library for conventions for inline references to code.
* Replace inline code blocks in docs (uses backticks) with formats following the conventions of the standard library.
Go doc does not have inline code blocks and backticks are unusual quotes for human readable documentation.
Closes #1713
> doc: remove ineffective inline code blocks
