- assert/assertions.go
- assert/assertions_test.go
- require/requirements.go
> Add assert.EqualValues, which attempts to convert types to test equality

- mock/mock.go
- mock/mock_test.go
You sometimes want to test concurrent behaviour like timeouts, but it was not currently possible with our mocks.
This PR adds the following functions to Mock:
`After` will block m.Called for the given duration before returning.
```go
func (m *Mock) After(d time.Duration) *Mock
Mock.On("MyMethod", arg1).After(1 * time.Millisecond)
```
`WaitUntil` is the primitive under `After`, and it's exposed in case you want somebody wants more control over the returns. `Called` blocks until the `w` channel is closed or receives a message.
```go
func (m *Mock) WaitUntil(w <-chan time.Time) *Mock
Mock.On("MyMethod", arg1).WaitUntil(time.After(1 * time.Millisecond))
```
> Mock can block returns with .After and .WaitUntil

- assert/doc.go
Also fixes missing right-bracket on Equal assertions.
> Doc entry for EqualValues assertion

- README.md
Please create a tag from this branch for `v1.0`.
> Updated README for versioning strategy

- mock/mock_test.go
> Mocking variadic functions

- mock/mock.go
mock: fix races to m.Calls/m.ExpectedCalls
> Fix data races

- assert/assertions.go
> Display actual and expected values on NotEqual

- assert/assertions.go
one more param order switch :)
> Fix param order in ObjectsAreEqualValues after type conversion

- mock/mock.go
The refactoring in 49804a38 reintroduced a race condition, which has been flagged by the race detector and is causing random failures of some of my tests.
Writes to an expected call's Repeatability field are still protected by the mutex in *Call.Times(), as well as in *Mock.Called(), but there is no protection for reads.  This commit corrects that with the minimal possible changes, although it's not terribly elegant.
It's unfortunate that the public API exposes mock.Calls, mock.ExpectedCalls, and other fields that are not safe for concurrent access, but I'm assuming the prior changes to fix race conditions in b11fb169 were partially motivated by a desire or need to avoid breaking that public API.  It may be a good idea to at least expose the mutex for consumers to safely access things, …
> fix race conditions related to mutation of expectedCall.Repeatability

- README.md
- suite/doc.go
Updated the README and suite/doc.go file.
> In README documentation of suite package #225

- .travis.yml
https://docs.travis-ci.com/user/workers/container-based-infrastructure/
> Add Go 1.6 and use container-based infrastructure

- mock/mock.go
Small change to comments to include correct usage of MatchedBy
> Update MatchedBy example to include actual use of MatchedBy!

- Godeps/Godeps.json
- vendor/github.com/davecgh/go-spew/LICENSE
- vendor/github.com/davecgh/go-spew/spew/bypass.go
- vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
- vendor/github.com/davecgh/go-spew/spew/config.go
> Fixes #348 - Update go-spew

- suite/suite.go
> Namespace suite flag `m` to `testify.m`

- mock/mock.go
"interface", was missing the 'r'
> Fixed minor typo

- assert/assertions.go
- assert/assertions_test.go
> assert: fix error reporting when error contains escape sequences

- mock/mock.go
> Fix race condition on mock package's Called

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
* Added new `assert.PanicsWithValue()` function, plus unit tests
Fixes #445
> Panics with value

- assert/assertions.go
> Fix actual float conversion error message under calcRelativeError

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- require/require.go
- require/require_forward.go
Fixes https://github.com/stretchr/testify/pull/500
PR was missing running `go generate`
> Minor doc typo

- mock/mock.go
- mock/mock_test.go
From: https://github.com/stretchr/testify/pull/410
New PR to be able to rebase on master
> Support nil arguments to Argument Matchers

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
Implement FileExists and DirExists assertions to check whether file/dir
exist in a given path.
Closes #428
> Add FileExists and DirExists assertions

- assert/assertions.go
> Correct typo in assert.InDeltaMapValues

- assert/assertions.go
Follow-up from https://github.com/stretchr/testify/pull/585
> More concrete error in Panics and PanicsWithValue

- assert/assertion_order.go
- assert/assertion_order_test.go
Add comparison methods https://github.com/stretchr/testify/issues/710
From the issue:
I have created a test collection comparisons there https://github.com/alexpantyukhin/assertord . I believe many of them are redundant but it's just for demo. Any thoughts could it be good idea to integrate that functionality into the `testify`? Also I guess it would be good to have `assert.IsGreater`, `assert.IsGreaterOrEqual`, `assert.IsLess`, `assert.IsLessOrEqual` in the `testify`.
> Add inequality assertions

- assert/assertions.go
- assert/assertions_test.go
- assert/forward_assertions_test.go
> Add panic stack to output from NotPanics assertion failures

- assert/assertion_format.go
- assert/assertion_forward.go
- go.mod
- require/require.go
- require/require_forward.go
* Added generated code for new assert & require tests
> Rerun go generate

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- go.sum
- require/require.go
- require/require_forward.go
* Added NotFileExists test
* Added NotDirExists test
* Cleaned-up some comment formatting
Closes #740
> Added negative dir and file tests

- README.md
> Update readme to include Slack channels

- CONTRIBUTING.md
- MAINTAINERS.md
Let's make things a little easier on people and provide some help for new maintainers!
@boyan-soubachov FYI
> Add some project docs

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- require/require.go
- require/require_forward.go
* Fixed the docstring for the InDelta function.
Fixes #860 (temporarily)
> Fix InDelta docstring

- assert/assertions.go
- assert/assertions_test.go
* Added `nil` function comparisons for `Equal`
Fixes #182
> Function comparisons for Equal

- assert/assertion_format.go
- assert/assertion_forward.go
- assert/assertions.go
- assert/assertions_test.go
- require/require.go
- require/require_forward.go
Closes #870 
Never asserts that a conditon isn't met within a given timeframe.
> Add Never assertion

- suite/suite.go
> suite: make suite.TestingT satisfy mock.TestingT

- suite/suite_test.go
@hugelgupf , test added for #881
> Add interface tests for suite.T

- CONTRIBUTING.md
- MAINTAINERS.md
> Add project / contributing documentation

- suite/suite.go
> fix(suite): Add Fatalf method to suite.TestingT for gomock compatibility

- assert/assertions_test.go
- http/test_response_writer.go
Just reads a bit nicer, in my opinion.
> Simplify go code

- assert/assertions_test.go
Probably just became obsolete by now.
> Removed unused variables

- assert/assertions.go
- mock/mock_test.go
Removed ineffectual assignments.
> Handle ineffectual assignments

- assert/assertions.go
- assert/assertions_test.go
> Test for #913

- .github/pull_request_template.md
Add a simple pull request template for future contributions to the repository
> Add GitHub pull request template

- suite/suite.go
> Rebase 'move teardown defers' by Aaron N Brock

- assert/assertions.go
Noticed this typo reading through the docs
> docs: update Comparison function comment

- README.md
> Change Readme to reflect supported Go versions

- .github/dependabot.yml
Allows dependabot to check dependencies and github actions versions
ADD dependabot config file
Keep dependencies and github actions up-to-date
> Set up Dependabot 

- .github/workflows/main.yml
- go.mod
Test old Go versions all the way back to 1.17.
> CI: tests from go1.17
